"use client";
import { useState } from "react";

type QueueItem = { toolId: string; toolName: string; status: string; sourceUrl: string | null; verifiedAt: string | null; plans: Array<{ name: string; price: { raw: string } }> };
type DashboardData = { configured: boolean; storageMode: "redis" | "local" | "unconfigured"; queue: QueueItem[]; feedback: Array<Record<string, string>>; audits: Array<Record<string, string>>; overrides: Record<string, unknown> };

export default function VerificationDashboard() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : sessionStorage.getItem("verification-token") ?? ""); const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<QueueItem | null>(null); const [status, setStatus] = useState("verified"); const [sourceUrl, setSourceUrl] = useState(""); const [note, setNote] = useState("");
  async function load(value = token) { setBusy(true); setError(""); try { const response = await fetch("/api/admin/verification", { headers: { Authorization: `Bearer ${value}` }, cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to load queue"); sessionStorage.setItem("verification-token", value); setData(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load queue"); } finally { setBusy(false); } }
  function select(item: QueueItem) { setSelected(item); setSourceUrl(item.sourceUrl ?? ""); setStatus("verified"); setNote(""); }
  async function save() { if (!selected) return; setBusy(true); setError(""); try { const response = await fetch("/api/admin/verification", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ action: "save-verification", toolId: selected.toolId, status, sourceUrl, note }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to save review"); setSelected(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save review"); } finally { setBusy(false); } }
  if (!data) return <div className="mx-auto max-w-xl px-5 py-20"><h1 className="text-3xl font-semibold">Verification desk</h1><form className="mt-8 border-y border-[#9eaaa4] py-6" onSubmit={(event) => { event.preventDefault(); load(); }}><label className="text-sm font-semibold" htmlFor="token">Admin token</label><input id="token" type="password" value={token} onChange={(event) => setToken(event.target.value)} className="mt-2 h-12 w-full border border-[#9eaaa4] bg-white px-3" autoComplete="current-password" /><button disabled={busy || !token} className="mt-4 min-h-11 bg-[#07110f] px-5 font-semibold text-white disabled:opacity-50">{busy ? "Checking..." : "Open desk"}</button>{error && <p role="alert" className="mt-4 text-sm text-[#8a3f2d]">{error}</p>}</form></div>;
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><header className="flex flex-col gap-4 border-b border-[#9eaaa4] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold">Verification desk</h1><p className="mt-2 text-[#596761]">{data.queue.length} pending records · {data.feedback.length} user reports · {data.audits.length} audit events</p></div><span className={`px-3 py-2 text-sm font-semibold ${data.configured ? "bg-[#d9f99d] text-[#174638]" : "bg-[#eee4d3] text-[#704d1f]"}`}>{data.storageMode === "redis" ? "Redis connected" : data.storageMode === "local" ? "Local development storage" : "Read-only: Redis not configured"}</span></header>
    {error && <p role="alert" className="mt-5 border border-[#b97b65] bg-[#f7e7df] p-4 text-sm text-[#703322]">{error}</p>}
    <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]"><section><h2 className="text-xl font-semibold">Pricing verification queue</h2><div className="mt-4 max-h-[70vh] overflow-auto border-y border-[#9eaaa4]"><table className="w-full min-w-[620px] text-left text-sm"><thead className="sticky top-0 bg-[#07110f] text-white"><tr><th className="p-3">Product</th><th className="p-3">State</th><th className="p-3">Plans</th><th className="p-3">Source</th><th className="p-3"><span className="sr-only">Review</span></th></tr></thead><tbody>{data.queue.map((item) => <tr key={item.toolId} className="border-b border-[#c2cbc5]"><td className="p-3 font-semibold">{item.toolName}</td><td className="p-3 font-mono text-xs">{item.status}</td><td className="p-3 font-mono">{item.plans.length}</td><td className="p-3">{item.sourceUrl ? <a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-[#285c4c] underline">Official</a> : "Missing"}</td><td className="p-3"><button onClick={() => select(item)} className="border border-[#285c4c] px-3 py-2 font-semibold text-[#285c4c]">Review</button></td></tr>)}</tbody></table></div></section>
      <aside className="lg:sticky lg:top-24 lg:self-start"><h2 className="text-xl font-semibold">Review record</h2>{selected ? <div className="mt-4 border-y border-[#9eaaa4] py-5"><div className="font-semibold">{selected.toolName}</div><label className="mt-5 block text-sm font-semibold">Decision<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-2 h-11 w-full border border-[#9eaaa4] bg-white px-3"><option value="verified">Verified</option><option value="needs_update">Needs update</option><option value="rejected">Reject source</option></select></label><label className="mt-4 block text-sm font-semibold">Official source<input value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} type="url" className="mt-2 h-11 w-full border border-[#9eaaa4] bg-white px-3" /></label><label className="mt-4 block text-sm font-semibold">Review note<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={5} className="mt-2 w-full border border-[#9eaaa4] bg-white p-3" /></label><div className="mt-5 flex gap-3"><button disabled={busy || !data.configured} onClick={save} className="min-h-11 bg-[#d9f99d] px-4 font-semibold disabled:opacity-50">Save review</button><button onClick={() => setSelected(null)} className="min-h-11 border border-[#9eaaa4] px-4">Cancel</button></div></div> : <p className="mt-4 border-y border-[#c2cbc5] py-8 text-sm text-[#68766f]">Select a record from the queue.</p>}</aside>
    </div></main>;
}
