// 第四批扩充：追加营销 SEO/社媒/邮件/网络安全/加密 Web3 等新分类，并补强视频剪辑、数据分析、3D、图片增强。
// 用法：node scripts/add-tools-4.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "data", "tools.json");

const newTools = [
  // ── 营销 SEO ─────────────────────────────
  { id: "semrush", name: "Semrush", nameZh: "Semrush", category: "seo", region: "overseas", description: "SEO 与数字营销工具套件，AI 关键词研究、竞品分析与内容优化。", descriptionEn: "SEO & digital marketing suite with AI keyword research, competitor analysis and content optimization.", officialUrl: "https://www.semrush.com", pricing: "trial", pricingNote: "试用后订阅", tags: ["SEO", "营销"], tagsEn: ["SEO", "Marketing"], score: 8.6, popularity: 74, emoji: "🎯", releaseYear: 2008, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "surfer-seo", name: "Surfer SEO", nameZh: "Surfer SEO", category: "seo", region: "overseas", description: "AI 内容优化工具，按搜索意图实时给文章打分与建议。", descriptionEn: "AI content optimization that scores and guides articles by search intent.", officialUrl: "https://surferseo.com", pricing: "paid", pricingNote: "订阅制", tags: ["SEO", "内容优化"], tagsEn: ["SEO", "Content"], score: 8.2, popularity: 60, emoji: "📝", releaseYear: 2017, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "ahrefs", name: "Ahrefs", nameZh: "Ahrefs", category: "seo", region: "overseas", description: "SEO 工具套件，AI 关键词、反链与站点审计。", descriptionEn: "SEO suite for AI keywords, backlinks and site audits.", officialUrl: "https://ahrefs.com", pricing: "trial", pricingNote: "试用后订阅", tags: ["SEO", "反链"], tagsEn: ["SEO", "Backlinks"], score: 8.5, popularity: 68, emoji: "🔗", releaseYear: 2011, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "frase", name: "Frase", nameZh: "Frase", category: "seo", region: "overseas", description: "AI 内容研究与 SEO 写作，自动生成大纲并优化排名。", descriptionEn: "AI content research and SEO writing with auto outlines and ranking optimization.", officialUrl: "https://www.frase.io", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["SEO", "写作"], tagsEn: ["SEO", "Writing"], score: 7.8, popularity: 52, emoji: "🔍", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "neuronwriter", name: "NeuronWriter", nameZh: "NeuronWriter", category: "seo", region: "overseas", description: "AI SEO 写作与内容优化，结合语义分析提升内容排名。", descriptionEn: "AI SEO writing and content optimization using semantic analysis.", officialUrl: "https://www.neuronwriter.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["SEO", "写作"], tagsEn: ["SEO", "Writing"], score: 7.7, popularity: 48, emoji: "✍️", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },

  // ── 社媒运营 ─────────────────────────────
  { id: "buffer", name: "Buffer", nameZh: "Buffer", category: "social", region: "overseas", description: "社媒排期与管理，AI 生成贴文与最佳发布时间。", descriptionEn: "Social scheduling and management with AI post generation and timing.", officialUrl: "https://buffer.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["社媒", "排期"], tagsEn: ["Social", "Scheduling"], score: 8.0, popularity: 62, emoji: "📅", releaseYear: 2010, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "sprout-social", name: "Sprout Social", nameZh: "Sprout Social", category: "social", region: "overseas", description: "社媒管理平台，AI 洞察、聆听与自动回复。", descriptionEn: "Social management platform with AI insights, listening and auto-replies.", officialUrl: "https://sproutsocial.com", pricing: "paid", pricingNote: "订阅制", tags: ["社媒", "洞察"], tagsEn: ["Social", "Insights"], score: 8.1, popularity: 58, emoji: "📊", releaseYear: 2010, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "hootsuite", name: "Hootsuite", nameZh: "Hootsuite", category: "social", region: "overseas", description: "社媒管理工具，AI 内容生成、排期与舆情监听。", descriptionEn: "Social management with AI content, scheduling and listening.", officialUrl: "https://www.hootsuite.com", pricing: "trial", pricingNote: "试用后订阅", tags: ["社媒", "监听"], tagsEn: ["Social", "Listening"], score: 7.9, popularity: 60, emoji: "🐦", releaseYear: 2008, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "typefully", name: "Typefully", nameZh: "Typefully", category: "social", region: "overseas", description: "X/Twitter 写作与排期，AI 优化推文与线程。", descriptionEn: "X/Twitter writing and scheduling with AI-optimized posts and threads.", officialUrl: "https://typefully.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["Twitter", "写作"], tagsEn: ["Twitter", "Writing"], score: 7.8, popularity: 54, emoji: "🐦", releaseYear: 2021, model: "GPT", modelEn: "GPT", platforms: ["web"], lastChecked: "2026-08" },
  { id: "publer", name: "Publer", nameZh: "Publer", category: "social", region: "overseas", description: "多平台社媒排期工具，AI 生成与优化贴文。", descriptionEn: "Multi-platform social scheduler with AI post generation and optimization.", officialUrl: "https://publer.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["社媒", "排期"], tagsEn: ["Social", "Scheduling"], score: 7.6, popularity: 46, emoji: "📤", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "later", name: "Later", nameZh: "Later", category: "social", region: "overseas", description: "Instagram 视觉排期工具，AI 生成文案与最佳时间。", descriptionEn: "Instagram visual scheduling with AI captions and optimal timing.", officialUrl: "https://later.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["Instagram", "排期"], tagsEn: ["Instagram", "Scheduling"], score: 7.5, popularity: 48, emoji: "📸", releaseYear: 2014, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },

  // ── 邮件工具 ─────────────────────────────
  { id: "superhuman", name: "Superhuman", nameZh: "Superhuman", category: "email", region: "overseas", description: "高速 AI 邮件客户端，智能分类、快捷回复与日程。", descriptionEn: "Fast AI email client with smart triage, quick replies and scheduling.", officialUrl: "https://superhuman.com", pricing: "paid", pricingNote: "订阅制", tags: ["邮件", "客户端"], tagsEn: ["Email", "Client"], score: 8.3, popularity: 62, emoji: "⚡", releaseYear: 2017, model: "自研", modelEn: "Proprietary", platforms: ["web", "macos", "ios"], trending: true, lastChecked: "2026-08" },
  { id: "shortwave", name: "Shortwave", nameZh: "Shortwave", category: "email", region: "overseas", description: "AI 邮件客户端，自动总结、安排与智能收件箱。", descriptionEn: "AI email client with auto summaries, scheduling and smart inbox.", officialUrl: "https://www.shortwave.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["邮件", "客户端"], tagsEn: ["Email", "Client"], score: 7.8, popularity: 52, emoji: "🌊", releaseYear: 2022, model: "GPT", modelEn: "GPT", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "klaviyo", name: "Klaviyo", nameZh: "Klaviyo", category: "email", region: "overseas", description: "电商邮件营销平台，AI 个性化与预测性发送。", descriptionEn: "E-commerce email marketing with AI personalization and predictive sending.", officialUrl: "https://www.klaviyo.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["邮件营销", "电商"], tagsEn: ["Email marketing", "E-commerce"], score: 8.1, popularity: 60, emoji: "📧", releaseYear: 2012, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "mailchimp", name: "Mailchimp", nameZh: "Mailchimp", category: "email", region: "overseas", description: "邮件营销与自动化平台，AI 生成内容与受众洞察。", descriptionEn: "Email marketing and automation with AI content and audience insights.", officialUrl: "https://mailchimp.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["邮件营销", "自动化"], tagsEn: ["Email marketing", "Automation"], score: 8.0, popularity: 66, emoji: "🐵", releaseYear: 2001, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "mixmax", name: "Mixmax", nameZh: "Mixmax", category: "email", region: "overseas", description: "销售邮件增强工具，AI 撰写、跟踪与自动化跟进。", descriptionEn: "Sales email enhancement with AI writing, tracking and automated follow-up.", officialUrl: "https://www.mixmax.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["销售邮件", "自动化"], tagsEn: ["Sales email", "Automation"], score: 7.6, popularity: 48, emoji: "✉️", releaseYear: 2014, model: "自研", modelEn: "Proprietary", platforms: ["web", "extension"], lastChecked: "2026-08" },
  { id: "sanebox", name: "SaneBox", nameZh: "SaneBox", category: "email", region: "overseas", description: "AI 邮件整理，自动分类、归档与提醒重要邮件。", descriptionEn: "AI email organization with auto-sorting, filing and important reminders.", officialUrl: "https://www.sanebox.com", pricing: "paid", pricingNote: "订阅制", tags: ["邮件", "整理"], tagsEn: ["Email", "Organization"], score: 7.5, popularity: 44, emoji: "🧹", releaseYear: 2010, model: "自研", modelEn: "Proprietary", platforms: ["web", "extension"], lastChecked: "2026-08" },

  // ── 网络安全 ─────────────────────────────
  { id: "crowdstrike", name: "CrowdStrike Falcon", nameZh: "CrowdStrike", category: "security", region: "overseas", description: "AI 原生端点安全平台，实时威胁检测与响应。", descriptionEn: "AI-native endpoint security with real-time threat detection and response.", officialUrl: "https://www.crowdstrike.com", pricing: "paid", pricingNote: "企业订阅", tags: ["端点安全", "威胁检测"], tagsEn: ["Endpoint", "Threat detection"], score: 8.6, popularity: 68, emoji: "🦅", releaseYear: 2011, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "darktrace", name: "Darktrace", nameZh: "Darktrace", category: "security", region: "overseas", description: "AI 网络威胁检测与自主响应，实时识别异常行为。", descriptionEn: "AI cyber threat detection and autonomous response for anomalies.", officialUrl: "https://darktrace.com", pricing: "paid", pricingNote: "企业订阅", tags: ["威胁检测", "响应"], tagsEn: ["Threat detection", "Response"], score: 8.2, popularity: 58, emoji: "🕵️", releaseYear: 2013, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "sentinelone", name: "SentinelOne", nameZh: "SentinelOne", category: "security", region: "overseas", description: "AI 驱动的端点防护平台，自动检测、响应与修复。", descriptionEn: "AI-driven endpoint protection with automatic detect, respond and remediate.", officialUrl: "https://www.sentinelone.com", pricing: "paid", pricingNote: "企业订阅", tags: ["端点防护", "AI"], tagsEn: ["Endpoint", "AI"], score: 8.1, popularity: 56, emoji: "🛡️", releaseYear: 2013, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "abnormal", name: "Abnormal Security", nameZh: "Abnormal Security", category: "security", region: "overseas", description: "AI 邮件安全，识别并拦截钓鱼、商业邮件欺诈与攻击。", descriptionEn: "AI email security that stops phishing, BEC and other attacks.", officialUrl: "https://abnormalsecurity.com", pricing: "paid", pricingNote: "企业订阅", tags: ["邮件安全", "反钓鱼"], tagsEn: ["Email security", "Anti-phishing"], score: 8.0, popularity: 52, emoji: "📧", releaseYear: 2018, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "vectra", name: "Vectra AI", nameZh: "Vectra AI", category: "security", region: "overseas", description: "AI 网络检测与响应（NDR），识别隐藏的网络攻击。", descriptionEn: "AI network detection and response that surfaces hidden attacks.", officialUrl: "https://www.vectra.ai", pricing: "paid", pricingNote: "企业订阅", tags: ["网络检测", "响应"], tagsEn: ["Network detection", "Response"], score: 7.8, popularity: 46, emoji: "🔍", releaseYear: 2010, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "snyk", name: "Snyk", nameZh: "Snyk", category: "security", region: "overseas", description: "开发者安全平台，AI 扫描并自动修复代码漏洞。", descriptionEn: "Developer security platform with AI scanning and auto-fixes for vulnerabilities.", officialUrl: "https://snyk.io", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["开发者安全", "漏洞"], tagsEn: ["Dev security", "Vulnerabilities"], score: 8.2, popularity: 56, emoji: "🔐", releaseYear: 2015, model: "自研", modelEn: "Proprietary", platforms: ["web", "extension", "api"], lastChecked: "2026-08" },

  // ── 加密 Web3 ─────────────────────────────
  { id: "chaingpt", name: "ChainGPT", nameZh: "ChainGPT", category: "crypto", region: "overseas", description: "Web3 领域的 AI 助手，链上问答、合约审计与 NFT 工具。", descriptionEn: "Web3-focused AI assistant for on-chain Q&A, contract audits and NFT tools.", officialUrl: "https://www.chaingpt.org", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["Web3", "合约"], tagsEn: ["Web3", "Contracts"], score: 7.6, popularity: 48, emoji: "🪙", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "nansen", name: "Nansen", nameZh: "Nansen", category: "crypto", region: "overseas", description: "链上数据分析平台，AI 洞察钱包行为、项目与趋势。", descriptionEn: "On-chain analytics with AI insights into wallets, projects and trends.", officialUrl: "https://www.nansen.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["链上数据", "分析"], tagsEn: ["On-chain", "Analytics"], score: 8.0, popularity: 54, emoji: "📊", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "moralis", name: "Moralis", nameZh: "Moralis", category: "crypto", region: "overseas", description: "Web3 数据与 API 平台，AI 索引链上数据供开发者使用。", descriptionEn: "Web3 data & API platform with AI-indexed on-chain data for developers.", officialUrl: "https://moralis.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["Web3", "API"], tagsEn: ["Web3", "API"], score: 7.7, popularity: 46, emoji: "🔗", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web", "api"], lastChecked: "2026-08" },
  { id: "kaito", name: "Kaito AI", nameZh: "Kaito AI", category: "crypto", region: "overseas", description: "加密领域的 AI 搜索引擎与信息平台，聚合全网情报。", descriptionEn: "Crypto-native AI search engine aggregating web-wide intelligence.", officialUrl: "https://www.kaito.ai", pricing: "free", pricingNote: "免费", tags: ["加密", "搜索"], tagsEn: ["Crypto", "Search"], score: 7.9, popularity: 50, emoji: "🧠", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], trending: true, lastChecked: "2026-08" },
  { id: "cookie3", name: "Cookie3", nameZh: "Cookie3", category: "crypto", region: "overseas", description: "链上用户行为分析 AI，识别真实用户与高价值钱包。", descriptionEn: "On-chain user-behavior AI that identifies real users and high-value wallets.", officialUrl: "https://www.cookie3.co", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["链上分析", "用户行为"], tagsEn: ["On-chain", "Behavior"], score: 7.4, popularity: 40, emoji: "🍪", releaseYear: 2022, model: "自研", modelEn: "Proprietary", platforms: ["web", "api"], lastChecked: "2026-08" },

  // ── 补强：视频剪辑 ─────────────────────────────
  { id: "kapwing", name: "Kapwing", nameZh: "Kapwing", category: "video-edit", region: "overseas", description: "在线视频编辑，AI 字幕、去背景与模板化剪辑。", descriptionEn: "Online video editor with AI subtitles, background removal and templates.", officialUrl: "https://www.kapwing.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["视频编辑", "字幕"], tagsEn: ["Video edit", "Subtitles"], score: 8.1, popularity: 60, emoji: "✂️", releaseYear: 2017, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "opus-clip", name: "Opus Clip", nameZh: "Opus Clip", category: "video-edit", region: "overseas", description: "AI 长视频转短视频，自动挑高光并生成竖版片段。", descriptionEn: "AI long-to-short video that auto-finds highlights and creates vertical clips.", officialUrl: "https://www.opus.pro", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["短视频", "剪辑"], tagsEn: ["Shorts", "Editing"], score: 8.0, popularity: 58, emoji: "🎬", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], trending: true, lastChecked: "2026-08" },
  { id: "submagic", name: "Submagic", nameZh: "Submagic", category: "video-edit", region: "overseas", description: "AI 字幕与短视频优化，自动加动态字幕、表情与音效。", descriptionEn: "AI subtitles and short-video optimization with dynamic captions and effects.", officialUrl: "https://www.submagic.co", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["字幕", "短视频"], tagsEn: ["Subtitles", "Shorts"], score: 7.8, popularity: 52, emoji: "💬", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "veed", name: "VEED.IO", nameZh: "VEED", category: "video-edit", region: "overseas", description: "AI 视频编辑，字幕、翻译、配音与去背景一体化。", descriptionEn: "AI video editing with subtitles, translation, dubbing and background removal.", officialUrl: "https://www.veed.io", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["视频编辑", "字幕"], tagsEn: ["Video edit", "Subtitles"], score: 8.0, popularity: 58, emoji: "🎥", releaseYear: 2018, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "descript", name: "Descript", nameZh: "Descript", category: "video-edit", region: "overseas", description: "文字即剪辑的 AI 音视频编辑器，改文字即可改视频。", descriptionEn: "AI audio/video editor where editing text edits the media.", officialUrl: "https://www.descript.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["视频编辑", "转录"], tagsEn: ["Video edit", "Transcription"], score: 8.2, popularity: 60, emoji: "🎙️", releaseYear: 2017, model: "自研", modelEn: "Proprietary", platforms: ["web", "macos", "windows"], verified: true, lastChecked: "2026-08" },

  // ── 补强：数据分析 ─────────────────────────────
  { id: "julius", name: "Julius AI", nameZh: "Julius AI", category: "data", region: "overseas", description: "AI 数据分析助手，用自然语言做图表、建模与洞察。", descriptionEn: "AI data analyst for charts, modeling and insights in natural language.", officialUrl: "https://julius.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["数据分析", "可视化"], tagsEn: ["Data", "Visualization"], score: 8.1, popularity: 58, emoji: "📊", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], trending: true, lastChecked: "2026-08" },
  { id: "rows", name: "Rows", nameZh: "Rows", category: "data", region: "overseas", description: "AI 表格与数据分析，公式、图表与集成自动化。", descriptionEn: "AI spreadsheet and data analysis with formulas, charts and integrations.", officialUrl: "https://rows.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["表格", "分析"], tagsEn: ["Spreadsheet", "Analysis"], score: 7.9, popularity: 50, emoji: "📈", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "akkio", name: "Akkio", nameZh: "Akkio", category: "data", region: "overseas", description: "无代码 AI 预测分析，自动训练模型并给出预测。", descriptionEn: "No-code AI predictive analytics with auto-trained models.", officialUrl: "https://www.akkio.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["预测分析", "无代码"], tagsEn: ["Predictive", "No-code"], score: 7.6, popularity: 42, emoji: "🧠", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "polymer", name: "Polymer", nameZh: "Polymer", category: "data", region: "overseas", description: "AI 数据可视化与仪表盘，无需代码即可洞察业务。", descriptionEn: "AI data visualization and dashboards for no-code business insights.", officialUrl: "https://www.polymersearch.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["可视化", "仪表盘"], tagsEn: ["Visualization", "Dashboard"], score: 7.5, popularity: 44, emoji: "📊", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "obviously-ai", name: "Obviously AI", nameZh: "Obviously AI", category: "data", region: "overseas", description: "无代码机器学习，上传数据即可做预测与分类。", descriptionEn: "No-code ML for prediction and classification from your data.", officialUrl: "https://www.obviously.ai", pricing: "paid", pricingNote: "订阅制", tags: ["机器学习", "无代码"], tagsEn: ["ML", "No-code"], score: 7.4, popularity: 40, emoji: "🔮", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },

  // ── 补强：3D 生成 ─────────────────────────────
  { id: "meshy", name: "Meshy", nameZh: "Meshy", category: "3d", region: "overseas", description: "文生 3D 模型，一键生成带贴图的 3D 资产。", descriptionEn: "Text-to-3D that generates textured 3D assets in one click.", officialUrl: "https://www.meshy.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["3D 生成", "贴图"], tagsEn: ["3D", "Texturing"], score: 8.0, popularity: 56, emoji: "🧊", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], trending: true, lastChecked: "2026-08" },
  { id: "tripo", name: "Tripo AI", nameZh: "Tripo AI", category: "3d", region: "overseas", description: "文/图生 3D 模型，快速生成可编辑的三维资产。", descriptionEn: "Text/image-to-3D for fast, editable 3D assets.", officialUrl: "https://www.tripo3d.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["3D 生成", "建模"], tagsEn: ["3D", "Modeling"], score: 7.8, popularity: 50, emoji: "📦", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "sloyd", name: "Sloyd", nameZh: "Sloyd", category: "3d", region: "overseas", description: "参数化 3D 生成，用滑块快速搭建游戏与场景资产。", descriptionEn: "Parametric 3D generation for quick game and scene assets via sliders.", officialUrl: "https://www.sloyd.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["3D", "游戏资产"], tagsEn: ["3D", "Game assets"], score: 7.5, popularity: 42, emoji: "🎮", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "spline", name: "Spline AI", nameZh: "Spline AI", category: "3d", region: "overseas", description: "AI 3D 设计与交互，用提示词生成和编辑 3D 场景。", descriptionEn: "AI 3D design and interaction, generating and editing scenes via prompts.", officialUrl: "https://spline.design", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["3D 设计", "交互"], tagsEn: ["3D design", "Interaction"], score: 7.7, popularity: 48, emoji: "✨", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web", "macos", "windows"], lastChecked: "2026-08" },
  { id: "kaedim", name: "Kaedim", nameZh: "Kaedim", category: "3d", region: "overseas", description: "图片转 3D 模型，从 2D 草图快速生成可用资产。", descriptionEn: "Image-to-3D that turns 2D sketches into usable assets.", officialUrl: "https://www.kaedim3d.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["图片转 3D", "建模"], tagsEn: ["Image-to-3D", "Modeling"], score: 7.4, popularity: 40, emoji: "🔺", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },

  // ── 补强：图片增强/修复 ─────────────────────────────
  { id: "remini", name: "Remini", nameZh: "Remini", category: "image-edit", region: "overseas", description: "AI 照片增强与老照片修复，一键提升清晰度与质感。", descriptionEn: "AI photo enhancement and restoration for clarity and quality.", officialUrl: "https://remini.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["照片增强", "修复"], tagsEn: ["Enhance", "Restore"], score: 8.1, popularity: 62, emoji: "📷", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], trending: true, lastChecked: "2026-08" },
  { id: "topaz", name: "Topaz Labs", nameZh: "Topaz Labs", category: "image-edit", region: "overseas", description: "专业 AI 照片与视频增强，降噪、锐化与放大。", descriptionEn: "Pro AI photo/video enhancement for denoise, sharpening and upscaling.", officialUrl: "https://www.topazlabs.com", pricing: "paid", pricingNote: "订阅制", tags: ["增强", "降噪"], tagsEn: ["Enhance", "Denoise"], score: 8.2, popularity: 54, emoji: "🖼️", releaseYear: 2009, model: "自研", modelEn: "Proprietary", platforms: ["windows", "macos"], verified: true, lastChecked: "2026-08" },
  { id: "magnific", name: "Magnific AI", nameZh: "Magnific AI", category: "image-edit", region: "overseas", description: "AI 图像放大与细节增强，为图像补足高分辨率细节。", descriptionEn: "AI upscaling and detail enhancement for high-res imagery.", officialUrl: "https://magnific.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["放大", "细节增强"], tagsEn: ["Upscale", "Detail"], score: 8.0, popularity: 56, emoji: "🔍", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "upscayl", name: "Upscayl", nameZh: "Upscayl", category: "image-edit", region: "overseas", description: "开源 AI 图像放大工具，本地运行、免费无损放大。", descriptionEn: "Open-source AI image upscaler that runs locally, free and lossless.", officialUrl: "https://www.upscayl.org", pricing: "free", pricingNote: "开源免费", tags: ["放大", "开源"], tagsEn: ["Upscale", "Open source"], score: 7.8, popularity: 50, emoji: "📐", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["windows", "macos", "linux"], lastChecked: "2026-08" },
  { id: "pixelcut", name: "Pixelcut", nameZh: "Pixelcut", category: "image-edit", region: "overseas", description: "AI 修图与电商图，去背景、扩图与产品图制作。", descriptionEn: "AI photo editing for e-commerce with background removal and product shots.", officialUrl: "https://www.pixelcut.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["去背景", "电商图"], tagsEn: ["Background removal", "Product"], score: 7.7, popularity: 48, emoji: "✂️", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
];

const tools = JSON.parse(readFileSync(dataPath, "utf8"));
const existing = new Set(tools.map((t) => t.id));

let added = 0;
const skipped = [];
for (const nt of newTools) {
  if (existing.has(nt.id)) {
    skipped.push(nt.id);
    continue;
  }
  tools.push(nt);
  added++;
}

writeFileSync(dataPath, JSON.stringify(tools, null, 2) + "\n", "utf8");
console.log(`added: ${added} new tools`);
if (skipped.length) console.log(`skipped (dup): ${skipped.join(", ")}`);
console.log(`total: ${tools.length} tools`);
