// 第二批扩充：追加音频/客服/法律/浏览器/提示词等新分类及补强现有分类的工具。
// 用法：node scripts/add-tools-2.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "data", "tools.json");

const newTools = [
  // ── 音频处理 ─────────────────────────────
  { id: "krisp", name: "Krisp", nameZh: "Krisp", category: "audio", region: "overseas", description: "AI 实时降噪，会议与通话中自动消除背景噪音与回声。", descriptionEn: "AI real-time noise cancellation that removes background noise and echo from calls.", officialUrl: "https://krisp.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["降噪", "会议"], tagsEn: ["Noise", "Meetings"], score: 8.2, popularity: 66, emoji: "🎧", releaseYear: 2017, model: "自研", modelEn: "Proprietary", platforms: ["web", "windows", "macos"], verified: true, lastChecked: "2026-08" },
  { id: "adobe-podcast", name: "Adobe Podcast", nameZh: "Adobe Podcast", category: "audio", region: "overseas", description: "AI 音频增强与修音，一键提升录音清晰度、去噪音。", descriptionEn: "AI audio enhancement that boosts recording clarity and removes noise in one click.", officialUrl: "https://podcast.adobe.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["音频增强", "播客"], tagsEn: ["Enhance", "Podcast"], score: 8.3, popularity: 64, emoji: "🎙️", releaseYear: 2022, model: "Adobe AI", modelEn: "Adobe AI", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "lalal-ai", name: "LALAL.AI", nameZh: "LALAL.AI", category: "audio", region: "overseas", description: "人声与伴奏分离工具，用 AI 从音乐中提取人声或乐器轨。", descriptionEn: "Vocal and instrumental stem separation using AI to isolate vocals or instruments.", officialUrl: "https://www.lalal.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["人声分离", "伴奏"], tagsEn: ["Stem", "Separation"], score: 7.8, popularity: 56, emoji: "🎼", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "auphonic", name: "Auphonic", nameZh: "Auphonic", category: "audio", region: "overseas", description: "自动音频后期处理，响度均衡、降噪与降噪混音。", descriptionEn: "Automatic audio post-production for loudness normalization, noise reduction and mixing.", officialUrl: "https://auphonic.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["后期", "响度"], tagsEn: ["Post-production", "Loudness"], score: 7.4, popularity: 44, emoji: "🎚️", releaseYear: 2011, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "moises", name: "Moises", nameZh: "Moises", category: "audio", region: "overseas", description: "音乐人工具，AI 分离人声/乐器、变调变速与降噪。", descriptionEn: "Musician tool with AI stem separation, key/tempo change and noise reduction.", officialUrl: "https://moises.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["人声分离", "音乐"], tagsEn: ["Stem", "Music"], score: 7.6, popularity: 52, emoji: "🎵", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "podcastle", name: "Podcastle", nameZh: "Podcastle", category: "audio", region: "overseas", description: "播客录制与 AI 编辑，自动转录、降噪与一键发布。", descriptionEn: "Podcast recording and AI editing with auto transcription, noise removal and publishing.", officialUrl: "https://podcastle.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["播客", "录制"], tagsEn: ["Podcast", "Recording"], score: 7.5, popularity: 48, emoji: "🎤", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios"], lastChecked: "2026-08" },
  { id: "wondercraft", name: "Wondercraft", nameZh: "Wondercraft", category: "audio", region: "overseas", description: "AI 播客制作平台，把文字快速变成专业播客。", descriptionEn: "AI podcast studio that turns text into professional podcasts fast.", officialUrl: "https://www.wondercraft.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["播客", "制作"], tagsEn: ["Podcast", "Production"], score: 7.3, popularity: 40, emoji: "🎧", releaseYear: 2023, model: "多模型", modelEn: "Multi-model", platforms: ["web"], lastChecked: "2026-08" },

  // ── 客服机器人 ─────────────────────────────
  { id: "intercom-fin", name: "Intercom Fin", nameZh: "Intercom Fin", category: "customer", region: "overseas", description: "Intercom 的 AI 客服机器人，基于知识库自动解答客户问题。", descriptionEn: "Intercom's AI support bot that answers customers from your knowledge base.", officialUrl: "https://www.intercom.com", pricing: "paid", pricingNote: "订阅制", tags: ["客服", "机器人"], tagsEn: ["Support", "Bot"], score: 8.5, popularity: 72, emoji: "🛎️", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "zendesk-ai", name: "Zendesk AI", nameZh: "Zendesk AI", category: "customer", region: "overseas", description: "Zendesk 的智能客服套件，自动分流、回复与总结工单。", descriptionEn: "Zendesk's AI support suite for auto-triage, replies and ticket summaries.", officialUrl: "https://www.zendesk.com", pricing: "paid", pricingNote: "订阅制", tags: ["客服", "工单"], tagsEn: ["Support", "Tickets"], score: 8.3, popularity: 66, emoji: "🎧", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "ada", name: "Ada", nameZh: "Ada", category: "customer", region: "overseas", description: "无代码 AI 客服机器人，自动处理常见问题与对话。", descriptionEn: "No-code AI customer service bot that automates FAQs and conversations.", officialUrl: "https://www.ada.cx", pricing: "paid", pricingNote: "订阅制", tags: ["客服", "无代码"], tagsEn: ["Support", "No-code"], score: 7.9, popularity: 58, emoji: "🤖", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "tidio-lyro", name: "Tidio Lyro", nameZh: "Tidio Lyro", category: "customer", region: "overseas", description: "电商场景的 AI 客服，自动回复售前咨询与订单问题。", descriptionEn: "E-commerce AI support that auto-answers pre-sales and order questions.", officialUrl: "https://www.tidio.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["客服", "电商"], tagsEn: ["Support", "E-commerce"], score: 7.7, popularity: 54, emoji: "🛍️", releaseYear: 2022, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "chatbase", name: "Chatbase", nameZh: "Chatbase", category: "customer", region: "overseas", description: "用你的知识库快速搭建 AI 客服机器人，无需代码。", descriptionEn: "Build an AI support chatbot from your knowledge base, no code required.", officialUrl: "https://www.chatbase.co", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["客服", "知识库"], tagsEn: ["Support", "Knowledge"], score: 7.8, popularity: 56, emoji: "💬", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], lastChecked: "2026-08" },
  { id: "botpress", name: "Botpress", nameZh: "Botpress", category: "customer", region: "overseas", description: "开源对话机器人与 Agent 平台，可自托管。", descriptionEn: "Open-source chatbot and agent platform with self-hosting.", officialUrl: "https://botpress.com", pricing: "freemium", pricingNote: "开源 + 云订阅", tags: ["机器人", "开源"], tagsEn: ["Chatbot", "Open source"], score: 7.6, popularity: 50, emoji: "🧩", releaseYear: 2016, model: "多模型", modelEn: "Multi-model", platforms: ["web"], lastChecked: "2026-08" },

  // ── 法律 ─────────────────────────────
  { id: "harvey-ai", name: "Harvey AI", nameZh: "Harvey AI", category: "legal", region: "overseas", description: "面向律所的法律 AI，合同分析、研究起草与合规。", descriptionEn: "Legal AI for law firms — contract analysis, research, drafting and compliance.", officialUrl: "https://www.harvey.ai", pricing: "paid", pricingNote: "企业订阅", tags: ["法律", "合同"], tagsEn: ["Legal", "Contracts"], score: 8.2, popularity: 58, emoji: "⚖️", releaseYear: 2022, model: "GPT", modelEn: "GPT", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "donotpay", name: "DoNotPay", nameZh: "DoNotPay", category: "legal", region: "overseas", description: "法律自助机器人，帮你写法律文书、申诉与维权。", descriptionEn: "Legal self-help bot for drafting documents, appeals and consumer claims.", officialUrl: "https://donotpay.com", pricing: "freemium", pricingNote: "订阅制", tags: ["法律", "自助"], tagsEn: ["Legal", "Self-help"], score: 7.5, popularity: 52, emoji: "⚖️", releaseYear: 2015, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "robin-ai", name: "Robin AI", nameZh: "Robin AI", category: "legal", region: "overseas", description: "AI 合同审查，快速识别风险条款与需要修改的地方。", descriptionEn: "AI contract review that flags risky clauses and needed edits.", officialUrl: "https://www.robinai.com", pricing: "paid", pricingNote: "企业订阅", tags: ["合同", "审查"], tagsEn: ["Contracts", "Review"], score: 7.7, popularity: 48, emoji: "📑", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "spellbook", name: "Spellbook", nameZh: "Spellbook", category: "legal", region: "overseas", description: "基于 GPT 的合同起草与审查助手，内置于 Word。", descriptionEn: "GPT-powered contract drafting and review assistant built into Word.", officialUrl: "https://www.spellbook.legal", pricing: "paid", pricingNote: "订阅制", tags: ["合同", "起草"], tagsEn: ["Contracts", "Drafting"], score: 7.6, popularity: 46, emoji: "📜", releaseYear: 2021, model: "GPT", modelEn: "GPT", platforms: ["web", "windows"], lastChecked: "2026-08" },
  { id: "casetext", name: "Casetext CoCounsel", nameZh: "Casetext", category: "legal", region: "overseas", description: "AI 法律检索与助手，用自然语言检索判例并生成法律分析。", descriptionEn: "AI legal research assistant that searches case law and generates analysis.", officialUrl: "https://casetext.com", pricing: "paid", pricingNote: "订阅制", tags: ["检索", "法律"], tagsEn: ["Research", "Legal"], score: 7.9, popularity: 50, emoji: "🔍", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], lastChecked: "2026-08" },

  // ── 浏览器 ─────────────────────────────
  { id: "arc", name: "Arc", nameZh: "Arc", category: "browser", region: "overseas", description: "AI 原生的现代浏览器，智能整理标签、自动归档与快速检索。", descriptionEn: "AI-native browser with smart tab organization, auto-archiving and quick search.", officialUrl: "https://arc.net", pricing: "free", pricingNote: "免费", tags: ["浏览器", "AI"], tagsEn: ["Browser", "AI"], score: 8.6, popularity: 74, emoji: "🧭", releaseYear: 2022, model: "自研", modelEn: "Proprietary", platforms: ["macos", "windows", "ios"], trending: true, lastChecked: "2026-08" },
  { id: "opera-aria", name: "Opera Aria", nameZh: "Opera", category: "browser", region: "overseas", description: "内置 AI 助手 Aria 的浏览器，侧边栏随时问答。", descriptionEn: "Browser with built-in AI assistant Aria for on-demand Q&A in the sidebar.", officialUrl: "https://www.opera.com", pricing: "free", pricingNote: "免费", tags: ["浏览器", "AI 助手"], tagsEn: ["Browser", "Assistant"], score: 7.8, popularity: 60, emoji: "🌐", releaseYear: 2023, model: "Aria", modelEn: "Aria", platforms: ["windows", "macos", "ios", "android"], lastChecked: "2026-08" },
  { id: "microsoft-edge", name: "Microsoft Edge Copilot", nameZh: "Edge Copilot", category: "browser", region: "overseas", description: "微软 Edge 内置 Copilot，侧边栏集成 GPT 问答与网页总结。", descriptionEn: "Microsoft Edge with built-in Copilot for GPT Q&A and page summaries in the sidebar.", officialUrl: "https://www.microsoft.com/edge", pricing: "free", pricingNote: "免费", tags: ["浏览器", "Copilot"], tagsEn: ["Browser", "Copilot"], score: 8.0, popularity: 62, emoji: "🌐", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["windows", "macos", "ios", "android"], verified: true, lastChecked: "2026-08" },
  { id: "sigmaos", name: "SigmaOS", nameZh: "SigmaOS", category: "browser", region: "overseas", description: "专注型 AI 浏览器，分屏工作区与 AI 摘要。", descriptionEn: "Focus-oriented AI browser with split workspaces and AI summaries.", officialUrl: "https://sigmaos.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["浏览器", "专注"], tagsEn: ["Browser", "Focus"], score: 7.2, popularity: 38, emoji: "✨", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["macos"], lastChecked: "2026-08" },

  // ── 提示词 ─────────────────────────────
  { id: "promptbase", name: "PromptBase", nameZh: "PromptBase", category: "prompt", region: "overseas", description: "提示词交易市场，买卖 Midjourney、ChatGPT 等优质提示词。", descriptionEn: "Prompt marketplace for buying and selling quality prompts for Midjourney, ChatGPT and more.", officialUrl: "https://promptbase.com", pricing: "paid", pricingNote: "按条购买", tags: ["提示词", "市场"], tagsEn: ["Prompts", "Marketplace"], score: 7.6, popularity: 48, emoji: "💡", releaseYear: 2022, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "flowgpt", name: "FlowGPT", nameZh: "FlowGPT", category: "prompt", region: "overseas", description: "提示词与 AI 角色社区，分享并发现热门提示词。", descriptionEn: "Prompt and AI character community to share and discover trending prompts.", officialUrl: "https://flowgpt.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["提示词", "社区"], tagsEn: ["Prompts", "Community"], score: 7.8, popularity: 56, emoji: "🧠", releaseYear: 2023, model: "多模型", modelEn: "Multi-model", platforms: ["web"], lastChecked: "2026-08" },
  { id: "snack-prompt", name: "Snack Prompt", nameZh: "Snack Prompt", category: "prompt", region: "overseas", description: "提示词社区与浏览器插件，随时调用优质提示词模板。", descriptionEn: "Prompt community and browser extension for quality prompt templates on demand.", officialUrl: "https://snackprompt.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["提示词", "模板"], tagsEn: ["Prompts", "Templates"], score: 7.3, popularity: 40, emoji: "🍿", releaseYear: 2023, model: "多模型", modelEn: "Multi-model", platforms: ["web", "extension"], lastChecked: "2026-08" },
  { id: "public-prompts", name: "Public Prompts", nameZh: "Public Prompts", category: "prompt", region: "overseas", description: "免费开源图像提示词库，提供 Stable Diffusion 风格模板。", descriptionEn: "Free open-source image prompt library with Stable Diffusion style templates.", officialUrl: "https://publicprompts.art", pricing: "free", pricingNote: "免费", tags: ["提示词", "图像"], tagsEn: ["Prompts", "Image"], score: 7.1, popularity: 36, emoji: "🖼️", releaseYear: 2022, model: "SD", modelEn: "SD", platforms: ["web"], lastChecked: "2026-08" },

  // ── 图像生成（补） ─────────────────────────────
  { id: "imagefx", name: "Google ImageFX", nameZh: "ImageFX", category: "image", region: "overseas", description: "谷歌的图像生成工具，基于 Gemini/Imagen，提示词交互友好。", descriptionEn: "Google's image generator built on Gemini/Imagen with friendly prompt controls.", officialUrl: "https://aitestkitchen.withgoogle.com/tools/image-fx", pricing: "free", pricingNote: "免费", tags: ["图像生成", "Google"], tagsEn: ["Image", "Google"], score: 8.4, popularity: 66, emoji: "🖼️", releaseYear: 2024, model: "Imagen (Gemini)", modelEn: "Imagen (Gemini)", platforms: ["web"], verified: true, trending: true, lastChecked: "2026-08" },
  { id: "meta-imagine", name: "Meta Imagine", nameZh: "Meta Imagine", category: "image", region: "overseas", description: "Meta 的 AI 图像生成，免费文生图与创意编辑。", descriptionEn: "Meta's AI image generator with free text-to-image and creative edits.", officialUrl: "https://imagine.meta.com", pricing: "free", pricingNote: "免费", tags: ["图像生成", "Meta"], tagsEn: ["Image", "Meta"], score: 7.8, popularity: 58, emoji: "🎨", releaseYear: 2023, model: "Llama / Emu", modelEn: "Llama / Emu", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "artbreeder", name: "Artbreeder", nameZh: "Artbreeder", category: "image", region: "overseas", description: "基因式图像混合与生成，通过组合与进化创造独特视觉。", descriptionEn: "Genetic image blending and generation for unique visuals through mixing and evolution.", officialUrl: "https://www.artbreeder.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["图像", "混合"], tagsEn: ["Image", "Blend"], score: 7.5, popularity: 52, emoji: "🧬", releaseYear: 2018, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "lexica", name: "Lexica", nameZh: "Lexica", category: "image", region: "overseas", description: "Stable Diffusion 图像搜索引擎，检索并生成 AI 图像。", descriptionEn: "Stable Diffusion image search engine to browse and generate AI images.", officialUrl: "https://lexica.art", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["图像", "搜索"], tagsEn: ["Image", "Search"], score: 7.6, popularity: 54, emoji: "🎨", releaseYear: 2022, model: "SD", modelEn: "SD", platforms: ["web"], lastChecked: "2026-08" },
  { id: "deepai", name: "DeepAI", nameZh: "DeepAI", category: "image", region: "overseas", description: "老牌 AI 图像生成与编辑站点，提供多种风格与免费额度。", descriptionEn: "Long-running AI image generation and editing site with many styles and free credits.", officialUrl: "https://deepai.org", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["图像生成", "编辑"], tagsEn: ["Image", "Edit"], score: 7.2, popularity: 44, emoji: "🤖", releaseYear: 2016, model: "多模型", modelEn: "Multi-model", platforms: ["web"], lastChecked: "2026-08" },

  // ── 视频生成（补） ─────────────────────────────
  { id: "haiper", name: "Haiper", nameZh: "Haiper", category: "video", region: "overseas", description: "AI 视频生成平台，文生视频与图生视频，由前 DeepMind 团队创办。", descriptionEn: "AI video generation platform for text/image-to-video, founded by ex-DeepMind researchers.", officialUrl: "https://haiper.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["文生视频", "图生视频"], tagsEn: ["Text-to-video", "Image-to-video"], score: 7.9, popularity: 58, emoji: "🎬", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "ltx-studio", name: "LTX Studio", nameZh: "LTX Studio", category: "video", region: "overseas", description: "AI 视频工作室，从脚本到分镜到成片的一体化生成。", descriptionEn: "AI video studio for integrated generation from script to storyboard to final cut.", officialUrl: "https://ltx.studio", pricing: "trial", pricingNote: "试用后订阅", tags: ["视频生成", "工作室"], tagsEn: ["Video", "Studio"], score: 7.7, popularity: 52, emoji: "🎥", releaseYear: 2024, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "higgsfield", name: "Higgsfield", nameZh: "Higgsfield", category: "video", region: "overseas", description: "AI 短视频生成，主打社交媒体风格的镜头与效果。", descriptionEn: "AI short-video generation focused on social-media-style shots and effects.", officialUrl: "https://higgsfield.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["短视频", "视频生成"], tagsEn: ["Shorts", "Video"], score: 7.6, popularity: 50, emoji: "📹", releaseYear: 2024, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios"], lastChecked: "2026-08" },
  { id: "google-vids", name: "Google Vids", nameZh: "Google Vids", category: "video", region: "overseas", description: "谷歌 Workspace 的 AI 视频制作，用文档与脚本一键生成视频。", descriptionEn: "Google Workspace AI video maker that turns docs and scripts into videos.", officialUrl: "https://workspace.google.com/products/vids/", pricing: "freemium", pricingNote: "Workspace 内置", tags: ["视频制作", "Google"], tagsEn: ["Video", "Google"], score: 8.0, popularity: 60, emoji: "🎞️", releaseYear: 2024, model: "Gemini", modelEn: "Gemini", platforms: ["web"], verified: true, lastChecked: "2026-08" },

  // ── 编程开发（补） ─────────────────────────────
  { id: "gemini-code-assist", name: "Gemini Code Assist", nameZh: "Gemini Code Assist", category: "code", region: "overseas", description: "谷歌的 AI 编程助手，IDE 内补全、生成与代码审查。", descriptionEn: "Google's AI coding assistant for completion, generation and review in the IDE.", officialUrl: "https://codeassist.google", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["编程", "Google"], tagsEn: ["Coding", "Google"], score: 8.1, popularity: 60, emoji: "💻", releaseYear: 2024, model: "Gemini", modelEn: "Gemini", platforms: ["web", "extension"], verified: true, lastChecked: "2026-08" },
  { id: "jetbrains-ai", name: "JetBrains AI Assistant", nameZh: "JetBrains AI", category: "code", region: "overseas", description: "JetBrains 全家桶内置的 AI 助手，补全、重构与解释代码。", descriptionEn: "JetBrains' built-in AI assistant for completion, refactoring and code explanation.", officialUrl: "https://www.jetbrains.com/ai/", pricing: "paid", pricingNote: "订阅制", tags: ["编程", "IDE"], tagsEn: ["Coding", "IDE"], score: 7.9, popularity: 56, emoji: "🧠", releaseYear: 2023, model: "多模型", modelEn: "Multi-model", platforms: ["desktop"], lastChecked: "2026-08" },
  { id: "continue", name: "Continue", nameZh: "Continue", category: "code", region: "overseas", description: "开源的 AI 代码助手，可接任意模型、本地或云端运行。", descriptionEn: "Open-source AI code assistant that works with any model, local or cloud.", officialUrl: "https://www.continue.dev", pricing: "free", pricingNote: "开源免费", tags: ["编程", "开源"], tagsEn: ["Coding", "Open source"], score: 7.7, popularity: 50, emoji: "🔌", releaseYear: 2023, model: "多模型", modelEn: "Multi-model", platforms: ["extension", "desktop"], lastChecked: "2026-08" },

  // ── 办公效率（补） ─────────────────────────────
  { id: "clickup-ai", name: "ClickUp AI", nameZh: "ClickUp AI", category: "office", region: "overseas", description: "ClickUp 项目管理内置 AI，写文档、总结与自动任务。", descriptionEn: "ClickUp's built-in AI for docs, summaries and task automation.", officialUrl: "https://clickup.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["项目管理", "协作"], tagsEn: ["Project", "Collaboration"], score: 8.0, popularity: 60, emoji: "✅", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web", "windows", "macos"], lastChecked: "2026-08" },
  { id: "motion", name: "Motion", nameZh: "Motion", category: "office", region: "overseas", description: "AI 日程与项目管理，自动安排任务和会议到日历。", descriptionEn: "AI scheduling and project management that auto-plans tasks and meetings.", officialUrl: "https://www.usemotion.com", pricing: "trial", pricingNote: "试用后订阅", tags: ["日程", "任务"], tagsEn: ["Scheduling", "Tasks"], score: 7.8, popularity: 54, emoji: "📅", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "reclaim-ai", name: "Reclaim AI", nameZh: "Reclaim AI", category: "office", region: "overseas", description: "智能日历，自动为你的任务与习惯预留时间。", descriptionEn: "Smart calendar that automatically reserves time for tasks and habits.", officialUrl: "https://reclaim.ai", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["日历", "日程"], tagsEn: ["Calendar", "Scheduling"], score: 7.7, popularity: 52, emoji: "🗓️", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web", "extension"], lastChecked: "2026-08" },

  // ── 写作助手（补） ─────────────────────────────
  { id: "anyword", name: "Anyword", nameZh: "Anyword", category: "writing", region: "overseas", description: "AI 营销文案，用预测评分帮你写出转化更高的文案。", descriptionEn: "AI marketing copy with predictive scoring for higher-converting text.", officialUrl: "https://anyword.com", pricing: "trial", pricingNote: "试用后订阅", tags: ["文案", "营销"], tagsEn: ["Copywriting", "Marketing"], score: 7.5, popularity: 48, emoji: "📈", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "hix-ai", name: "Hix AI", nameZh: "Hix AI", category: "writing", region: "overseas", description: "全能 AI 写作助手，覆盖文章、邮件、文案与改写。", descriptionEn: "All-in-one AI writing assistant for articles, emails, copy and rewriting.", officialUrl: "https://hix.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["写作", "改写"], tagsEn: ["Writing", "Rewrite"], score: 7.4, popularity: 46, emoji: "✍️", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], lastChecked: "2026-08" },

  // ── 语音（补） ─────────────────────────────
  { id: "openai-whisper", name: "OpenAI Whisper", nameZh: "Whisper", category: "voice", region: "overseas", description: "开源语音识别模型，支持多语言转写与翻译。", descriptionEn: "Open-source speech recognition model for multilingual transcription and translation.", officialUrl: "https://openai.com", pricing: "free", pricingNote: "开源免费", tags: ["语音识别", "转写"], tagsEn: ["ASR", "Transcription"], score: 8.4, popularity: 64, emoji: "🎤", releaseYear: 2022, model: "Whisper", modelEn: "Whisper", platforms: ["api", "desktop"], verified: true, lastChecked: "2026-08" },
  { id: "coqui", name: "Coqui", nameZh: "Coqui", category: "voice", region: "overseas", description: "开源语音合成平台，支持声音克隆与多语言 TTS。", descriptionEn: "Open-source speech platform with voice cloning and multilingual TTS.", officialUrl: "https://coqui.ai", pricing: "free", pricingNote: "开源免费", tags: ["语音合成", "开源"], tagsEn: ["TTS", "Open source"], score: 7.3, popularity: 42, emoji: "🗣️", releaseYear: 2021, model: "XTTS", modelEn: "XTTS", platforms: ["web", "api"], lastChecked: "2026-08" },
];

const tools = JSON.parse(readFileSync(dataPath, "utf8"));
const existing = new Set(tools.map((t) => t.id));

let added = 0;
const skipped = [];
for (const nt of newTools) {
  if (existing.has(nt.id)) {
    skipped.push(nt.id);
    continue;
  }
  tools.push(nt);
  added++;
}

writeFileSync(dataPath, JSON.stringify(tools, null, 2) + "\n", "utf8");
console.log(`added: ${added} new tools`);
if (skipped.length) console.log(`skipped (dup): ${skipped.join(", ")}`);
console.log(`total: ${tools.length} tools`);
