// 第三批扩充：追加健康医疗/金融/招聘/电商/游戏/旅行等新分类，并补强对话、搜索、视频、编程、设计、教育、PDF、研究等现有分类。
// 用法：node scripts/add-tools-3.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "data", "tools.json");

const newTools = [
  // ── 健康医疗 ─────────────────────────────
  { id: "ada-health", name: "Ada", nameZh: "Ada 健康", category: "health", region: "overseas", description: "AI 症状评估助手，输入症状帮你判断可能原因与就医建议。", descriptionEn: "AI symptom assessment that helps identify possible causes and next steps.", officialUrl: "https://ada.com", pricing: "freemium", pricingNote: "免费 + 服务", tags: ["症状评估", "健康"], tagsEn: ["Symptom", "Health"], score: 7.8, popularity: 56, emoji: "🩺", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "buoy", name: "Buoy Health", nameZh: "Buoy Health", category: "health", region: "overseas", description: "AI 症状检查，用对话式问答帮你快速了解身体状况。", descriptionEn: "AI symptom checker using conversational Q&A to understand your condition.", officialUrl: "https://www.buoyhealth.com", pricing: "free", pricingNote: "免费", tags: ["症状检查", "健康"], tagsEn: ["Symptom", "Health"], score: 7.6, popularity: 52, emoji: "🌡️", releaseYear: 2014, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "woebot", name: "Woebot", nameZh: "Woebot", category: "health", region: "overseas", description: "心理健康 AI 伙伴，用认知行为疗法（CBT）对话缓解焦虑情绪。", descriptionEn: "Mental health AI companion using CBT-based chat to ease anxiety and mood.", officialUrl: "https://woebothealth.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["心理健康", "CBT"], tagsEn: ["Mental health", "CBT"], score: 7.5, popularity: 50, emoji: "🧠", releaseYear: 2017, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "wysa", name: "Wysa", nameZh: "Wysa", category: "health", region: "overseas", description: "匿名 AI 心理陪伴，支持情绪支持与自助冥想练习。", descriptionEn: "Anonymous AI emotional support with self-help and mindfulness exercises.", officialUrl: "https://www.wysa.com", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["心理", "陪伴"], tagsEn: ["Mental", "Support"], score: 7.4, popularity: 48, emoji: "💙", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "abridge", name: "Abridge", nameZh: "Abridge", category: "health", region: "overseas", description: "面向医疗场景的 AI 对话转写与病历整理，自动生成就诊摘要。", descriptionEn: "Medical AI that transcribes conversations and generates visit summaries.", officialUrl: "https://www.abridge.com", pricing: "paid", pricingNote: "企业订阅", tags: ["医疗", "转写"], tagsEn: ["Medical", "Transcription"], score: 7.9, popularity: 54, emoji: "📋", releaseYear: 2018, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], verified: true, lastChecked: "2026-08" },
  { id: "corti", name: "Corti", nameZh: "Corti", category: "health", region: "overseas", description: "医疗决策支持 AI，实时辅助急救与临床问诊。", descriptionEn: "Medical decision-support AI for real-time emergency and clinical triage.", officialUrl: "https://www.corti.ai", pricing: "paid", pricingNote: "企业订阅", tags: ["医疗", "决策支持"], tagsEn: ["Medical", "Decision"], score: 7.7, popularity: 46, emoji: "🩺", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },

  // ── 金融投资 ─────────────────────────────
  { id: "finchat", name: "FinChat.io", nameZh: "FinChat", category: "finance", region: "overseas", description: "AI 股票研究助手，用自然语言查询公司财务与估值数据。", descriptionEn: "AI stock research assistant for querying company financials and valuation.", officialUrl: "https://finchat.io", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["投研", "股票"], tagsEn: ["Investing", "Stocks"], score: 8.0, popularity: 58, emoji: "📈", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "magnifi", name: "Magnifi", nameZh: "Magnifi", category: "finance", region: "overseas", description: "AI 投资研究平台，用自然语言分析基金、ETF 与股票。", descriptionEn: "AI investment research for funds, ETFs and stocks via natural language.", officialUrl: "https://magnifi.com", pricing: "paid", pricingNote: "订阅制", tags: ["投研", "基金"], tagsEn: ["Investing", "Funds"], score: 7.5, popularity: 42, emoji: "💹", releaseYear: 2019, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "kavout", name: "Kavout", nameZh: "Kavout", category: "finance", region: "overseas", description: "AI 选股与量化信号，用机器学习给股票打分排序。", descriptionEn: "AI stock picking with machine-learning scoring and quantitative signals.", officialUrl: "https://www.kavout.com", pricing: "paid", pricingNote: "订阅制", tags: ["选股", "量化"], tagsEn: ["Stock", "Quant"], score: 7.3, popularity: 38, emoji: "📊", releaseYear: 2015, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "wealthfront", name: "Wealthfront", nameZh: "Wealthfront", category: "finance", region: "overseas", description: "智能投顾（Robo-advisor），自动配置投资组合与再平衡。", descriptionEn: "Robo-advisor that auto-allocates and rebalances your portfolio.", officialUrl: "https://www.wealthfront.com", pricing: "freemium", pricingNote: "低费率", tags: ["智能投顾", "理财"], tagsEn: ["Robo-advisor", "Wealth"], score: 7.8, popularity: 52, emoji: "🤖", releaseYear: 2011, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], verified: true, lastChecked: "2026-08" },
  { id: "betterment", name: "Betterment", nameZh: "Betterment", category: "finance", region: "overseas", description: "老牌智能投顾，自动投资与退休规划。", descriptionEn: "Pioneering robo-advisor for automated investing and retirement planning.", officialUrl: "https://www.betterment.com", pricing: "freemium", pricingNote: "低费率", tags: ["智能投顾", "退休"], tagsEn: ["Robo-advisor", "Retirement"], score: 7.7, popularity: 50, emoji: "🏦", releaseYear: 2008, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "alpaca", name: "Alpaca", nameZh: "Alpaca", category: "finance", region: "overseas", description: "交易 API 平台，让开发者用代码搭建自动化交易与 AI 策略。", descriptionEn: "Trading API platform for building automated and AI-driven strategies.", officialUrl: "https://alpaca.markets", pricing: "freemium", pricingNote: "免费 + 佣金", tags: ["交易 API", "量化"], tagsEn: ["Trading", "API"], score: 7.6, popularity: 46, emoji: "🔌", releaseYear: 2015, model: "自研", modelEn: "Proprietary", platforms: ["web", "api"], lastChecked: "2026-08" },

  // ── 招聘人事 ─────────────────────────────
  { id: "hirevue", name: "HireVue", nameZh: "HireVue", category: "hr", region: "overseas", description: "AI 视频面试与候选人评估，自动分析表达与胜任力。", descriptionEn: "AI video interviews and candidate assessment with competency analysis.", officialUrl: "https://www.hirevue.com", pricing: "paid", pricingNote: "企业订阅", tags: ["面试", "招聘"], tagsEn: ["Interview", "Recruiting"], score: 7.8, popularity: 54, emoji: "🎥", releaseYear: 2004, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, lastChecked: "2026-08" },
  { id: "eightfold", name: "Eightfold AI", nameZh: "Eightfold AI", category: "hr", region: "overseas", description: "人才智能平台，用 AI 匹配岗位与候选人、做内部人才盘点。", descriptionEn: "Talent intelligence platform matching roles and candidates via AI.", officialUrl: "https://eightfold.ai", pricing: "paid", pricingNote: "企业订阅", tags: ["人才", "匹配"], tagsEn: ["Talent", "Matching"], score: 7.7, popularity: 50, emoji: "🧩", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "seekout", name: "SeekOut", nameZh: "SeekOut", category: "hr", region: "overseas", description: "人才搜索与招募平台，聚合多渠道简历与候选人画像。", descriptionEn: "Talent sourcing platform aggregating profiles and candidate insights.", officialUrl: "https://www.seekout.com", pricing: "paid", pricingNote: "企业订阅", tags: ["人才搜索", "招聘"], tagsEn: ["Sourcing", "Recruiting"], score: 7.5, popularity: 44, emoji: "🔍", releaseYear: 2018, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "textio", name: "Textio", nameZh: "Textio", category: "hr", region: "overseas", description: "AI 招聘文案优化，帮你写出更包容、更有吸引力的职位描述。", descriptionEn: "AI that optimizes job posts for inclusivity and appeal.", officialUrl: "https://textio.com", pricing: "paid", pricingNote: "订阅制", tags: ["招聘文案", "优化"], tagsEn: ["Job posts", "Optimization"], score: 7.4, popularity: 42, emoji: "✍️", releaseYear: 2014, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "fetcher", name: "Fetcher", nameZh: "Fetcher", category: "hr", region: "overseas", description: "AI 主动寻源助手，自动寻找并联系潜在候选人。", descriptionEn: "AI sourcing assistant that finds and reaches out to potential candidates.", officialUrl: "https://www.fetcher.ai", pricing: "paid", pricingNote: "订阅制", tags: ["寻源", "招聘"], tagsEn: ["Sourcing", "Recruiting"], score: 7.3, popularity: 40, emoji: "📬", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },

  // ── 电商运营 ─────────────────────────────
  { id: "shopify-magic", name: "Shopify Magic", nameZh: "Shopify Magic", category: "ecommerce", region: "overseas", description: "Shopify 内置的电商 AI，自动生成商品文案、图片与客服回复。", descriptionEn: "Shopify's built-in AI for listing copy, images and support replies.", officialUrl: "https://www.shopify.com/magic", pricing: "freemium", pricingNote: "平台内置", tags: ["电商", "文案"], tagsEn: ["E-commerce", "Copy"], score: 8.2, popularity: 62, emoji: "🪄", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], verified: true, trending: true, lastChecked: "2026-08" },
  { id: "pebblely", name: "Pebblely", nameZh: "Pebblely", category: "ecommerce", region: "overseas", description: "AI 产品图生成，把产品照片放到任意场景背景中。", descriptionEn: "AI product photography that places products into any scene background.", officialUrl: "https://pebblely.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["产品图", "电商"], tagsEn: ["Product photo", "E-commerce"], score: 7.7, popularity: 50, emoji: "📦", releaseYear: 2022, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "flair", name: "Flair AI", nameZh: "Flair AI", category: "ecommerce", region: "overseas", description: "AI 产品摄影与品牌素材，拖拽即可生成专业商品图。", descriptionEn: "AI product photography and brand assets via drag-and-drop.", officialUrl: "https://flair.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["产品摄影", "电商"], tagsEn: ["Photography", "E-commerce"], score: 7.6, popularity: 48, emoji: "📸", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "vue-ai", name: "Vue.ai", nameZh: "Vue.ai", category: "ecommerce", region: "overseas", description: "零售电商视觉 AI，自动为商品打标签、生成搭配与视觉搜索。", descriptionEn: "Retail visual AI for auto-tagging, styling and visual search.", officialUrl: "https://vue.ai", pricing: "paid", pricingNote: "企业订阅", tags: ["视觉 AI", "零售"], tagsEn: ["Visual AI", "Retail"], score: 7.4, popularity: 40, emoji: "👗", releaseYear: 2016, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "heyday", name: "Heyday", nameZh: "Heyday", category: "ecommerce", region: "overseas", description: "电商 AI 客服，自动回答商品咨询并提升转化。", descriptionEn: "E-commerce AI support that answers product questions and boosts conversion.", officialUrl: "https://www.heyday.ai", pricing: "paid", pricingNote: "订阅制", tags: ["电商客服", "转化"], tagsEn: ["Support", "Conversion"], score: 7.5, popularity: 44, emoji: "💬", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "syte", name: "Syte", nameZh: "Syte", category: "ecommerce", region: "overseas", description: "电商视觉搜索，拍张照片就能找到相似商品。", descriptionEn: "Visual search for e-commerce — snap a photo to find similar products.", officialUrl: "https://www.syte.ai", pricing: "paid", pricingNote: "企业订阅", tags: ["视觉搜索", "电商"], tagsEn: ["Visual search", "E-commerce"], score: 7.3, popularity: 38, emoji: "🖼️", releaseYear: 2015, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },

  // ── 游戏娱乐 ─────────────────────────────
  { id: "unity-muse", name: "Unity Muse", nameZh: "Unity Muse", category: "gaming", region: "overseas", description: "Unity 的 AI 游戏开发套件，生成贴图、动画与行为。", descriptionEn: "Unity's AI game-dev suite for textures, animation and behaviors.", officialUrl: "https://unity.com/products/muse", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["游戏开发", "资产生成"], tagsEn: ["Game dev", "Assets"], score: 7.9, popularity: 54, emoji: "🎮", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web", "desktop"], verified: true, lastChecked: "2026-08" },
  { id: "inworld", name: "Inworld AI", nameZh: "Inworld AI", category: "gaming", region: "overseas", description: "游戏 NPC 引擎，为虚拟角色赋予感知、记忆与个性。", descriptionEn: "Game NPC engine giving virtual characters perception, memory and personality.", officialUrl: "https://inworld.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["NPC", "游戏"], tagsEn: ["NPC", "Game"], score: 7.8, popularity: 50, emoji: "🧝", releaseYear: 2021, model: "多模型", modelEn: "Multi-model", platforms: ["web", "api"], lastChecked: "2026-08" },
  { id: "scenario", name: "Scenario", nameZh: "Scenario", category: "gaming", region: "overseas", description: "游戏资产生成平台，用 AI 批量生成风格一致的插画与贴图。", descriptionEn: "Game asset platform for AI-generated, style-consistent art and textures.", officialUrl: "https://www.scenario.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["资产生成", "游戏"], tagsEn: ["Assets", "Game"], score: 7.6, popularity: 46, emoji: "🎨", releaseYear: 2021, model: "SD", modelEn: "SD", platforms: ["web"], lastChecked: "2026-08" },
  { id: "ai-dungeon", name: "AI Dungeon", nameZh: "AI Dungeon", category: "gaming", region: "overseas", description: "AI 文字冒险游戏，无限生成互动故事与角色扮演。", descriptionEn: "AI text adventure with infinite interactive stories and roleplay.", officialUrl: "https://aidungeon.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["文字游戏", "叙事"], tagsEn: ["Text game", "Story"], score: 7.5, popularity: 48, emoji: "📜", releaseYear: 2019, model: "GPT", modelEn: "GPT", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "ludo-ai", name: "Ludo.ai", nameZh: "Ludo.ai", category: "gaming", region: "overseas", description: "游戏创意与调研 AI，帮你发现玩法、生成概念与原型。", descriptionEn: "Game ideation and research AI for concepts and prototypes.", officialUrl: "https://ludo.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["创意", "游戏"], tagsEn: ["Ideation", "Game"], score: 7.3, popularity: 40, emoji: "🧠", releaseYear: 2020, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "nvidia-ace", name: "Nvidia ACE", nameZh: "Nvidia ACE", category: "gaming", region: "overseas", description: "NVIDIA 的数字人/NPC 技术，为游戏角色带来实时对话 AI。", descriptionEn: "NVIDIA's digital-human/NPC tech for real-time conversational game characters.", officialUrl: "https://www.nvidia.com/en-us/omniverse/ace/", pricing: "free", pricingNote: "SDK 免费", tags: ["NPC", "数字人"], tagsEn: ["NPC", "Digital human"], score: 8.1, popularity: 52, emoji: "🤖", releaseYear: 2024, model: "多模型", modelEn: "Multi-model", platforms: ["api"], verified: true, lastChecked: "2026-08" },

  // ── 旅行出行 ─────────────────────────────
  { id: "guidegeek", name: "GuideGeek", nameZh: "GuideGeek", category: "travel", region: "overseas", description: "AI 旅行助手，在 WhatsApp 上实时问答目的地、行程与预订。", descriptionEn: "AI travel assistant for real-time destination and itinerary help on WhatsApp.", officialUrl: "https://www.guidegeek.com", pricing: "free", pricingNote: "免费", tags: ["旅行", "助手"], tagsEn: ["Travel", "Assistant"], score: 7.6, popularity: 48, emoji: "🧭", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web", "wechat"], lastChecked: "2026-08" },
  { id: "layla", name: "Layla", nameZh: "Layla", category: "travel", region: "overseas", description: "AI 旅行规划，输入想法自动生成行程、景点与路线。", descriptionEn: "AI trip planner that turns ideas into itineraries, spots and routes.", officialUrl: "https://layla.ai", pricing: "free", pricingNote: "免费", tags: ["旅行规划", "行程"], tagsEn: ["Planning", "Itinerary"], score: 7.7, popularity: 50, emoji: "✈️", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web", "ios", "android"], lastChecked: "2026-08" },
  { id: "wanderboat", name: "Wanderboat", nameZh: "Wanderboat", category: "travel", region: "overseas", description: "AI 旅行规划与灵感，生成个性化行程与本地推荐。", descriptionEn: "AI travel planning and inspiration for personalized itineraries and local tips.", officialUrl: "https://wanderboat.ai", pricing: "free", pricingNote: "免费", tags: ["旅行规划", "推荐"], tagsEn: ["Planning", "Recommendations"], score: 7.4, popularity: 42, emoji: "🗺️", releaseYear: 2023, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "tripplanner", name: "TripPlanner AI", nameZh: "TripPlanner AI", category: "travel", region: "overseas", description: "AI 行程规划工具，快速生成逐日行程与预算方案。", descriptionEn: "AI itinerary tool for day-by-day plans and budgets.", officialUrl: "https://tripplanner.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["行程", "规划"], tagsEn: ["Itinerary", "Planning"], score: 7.3, popularity: 40, emoji: "🧳", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], lastChecked: "2026-08" },
  { id: "hopper", name: "Hopper", nameZh: "Hopper", category: "travel", region: "overseas", description: "AI 机票与酒店价格预测，告诉你何时买最划算。", descriptionEn: "AI flight and hotel price prediction to tell you when to book.", officialUrl: "https://www.hopper.com", pricing: "free", pricingNote: "免费", tags: ["机票", "价格预测"], tagsEn: ["Flights", "Price prediction"], score: 7.8, popularity: 54, emoji: "✈️", releaseYear: 2007, model: "自研", modelEn: "Proprietary", platforms: ["web", "ios", "android"], verified: true, lastChecked: "2026-08" },

  // ── 补强：对话助手 ─────────────────────────────
  { id: "grok", name: "Grok", nameZh: "Grok", category: "chat", region: "overseas", description: "xAI 推出的 AI 助手，接入 X 平台实时信息，风格直率。", descriptionEn: "xAI's assistant with real-time X platform context and a direct style.", officialUrl: "https://grok.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["对话", "实时信息"], tagsEn: ["Chat", "Real-time"], score: 8.5, popularity: 78, emoji: "🧠", releaseYear: 2023, model: "Grok", modelEn: "Grok", platforms: ["web", "ios", "android"], verified: true, trending: true, lastChecked: "2026-08" },
  { id: "mistral", name: "Mistral Le Chat", nameZh: "Mistral", category: "chat", region: "overseas", description: "欧洲 Mistral AI 的对话助手，开源模型出身、速度快。", descriptionEn: "Mistral AI's assistant, fast and built on open models.", officialUrl: "https://mistral.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["对话", "开源"], tagsEn: ["Chat", "Open source"], score: 8.1, popularity: 62, emoji: "🗣️", releaseYear: 2024, model: "Mistral", modelEn: "Mistral", platforms: ["web", "ios", "android"], verified: true, lastChecked: "2026-08" },
  { id: "meta-ai", name: "Meta AI", nameZh: "Meta AI", category: "chat", region: "overseas", description: "Meta 的 AI 助手，内置于 WhatsApp、Instagram 与 Messenger。", descriptionEn: "Meta's assistant built into WhatsApp, Instagram and Messenger.", officialUrl: "https://www.meta.ai", pricing: "free", pricingNote: "免费", tags: ["对话", "Meta"], tagsEn: ["Chat", "Meta"], score: 8.0, popularity: 64, emoji: "🌐", releaseYear: 2023, model: "Llama", modelEn: "Llama", platforms: ["web", "ios", "android"], verified: true, lastChecked: "2026-08" },

  // ── 补强：AI 搜索 ─────────────────────────────
  { id: "exa", name: "Exa", nameZh: "Exa", category: "search", region: "overseas", description: "面向 AI 应用的搜索 API，用语义理解检索全网信息。", descriptionEn: "Search API for AI apps, retrieving the web with semantic understanding.", officialUrl: "https://exa.ai", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["搜索 API", "语义"], tagsEn: ["Search", "Semantic"], score: 8.2, popularity: 56, emoji: "🔍", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web", "api"], lastChecked: "2026-08" },

  // ── 补强：视频生成 ─────────────────────────────
  { id: "vidu", name: "Vidu", nameZh: "Vidu", category: "video", region: "domestic", description: "生数科技的视频生成模型，支持文生视频、图生视频与多主体一致性。", descriptionEn: "Shengshu's video model for text/image-to-video with multi-subject consistency.", officialUrl: "https://www.vidu.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["文生视频", "图生视频"], tagsEn: ["Text-to-video", "Image-to-video"], score: 7.9, popularity: 56, emoji: "🎬", releaseYear: 2024, model: "Vidu", modelEn: "Vidu", platforms: ["web"], verified: true, lastChecked: "2026-08" },

  // ── 补强：编程开发 ─────────────────────────────
  { id: "warp", name: "Warp", nameZh: "Warp", category: "code", region: "overseas", description: "AI 原生终端，自然语言写命令、自动补全与协作。", descriptionEn: "AI-native terminal with natural-language commands and autocomplete.", officialUrl: "https://www.warp.dev", pricing: "freemium", pricingNote: "免费 + 订阅", tags: ["终端", "编程"], tagsEn: ["Terminal", "Coding"], score: 8.0, popularity: 58, emoji: "⌨️", releaseYear: 2021, model: "多模型", modelEn: "Multi-model", platforms: ["macos", "linux", "windows"], lastChecked: "2026-08" },

  // ── 补强：设计创意 ─────────────────────────────
  { id: "relume", name: "Relume", nameZh: "Relume", category: "design", region: "overseas", description: "AI 网站设计工具，生成站点地图、线框图并一键导出到 Webflow。", descriptionEn: "AI web design tool for sitemaps, wireframes and Webflow export.", officialUrl: "https://www.relume.io", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["网站设计", "线框图"], tagsEn: ["Web design", "Wireframe"], score: 7.8, popularity: 52, emoji: "🧩", releaseYear: 2021, model: "自研", modelEn: "Proprietary", platforms: ["web"], lastChecked: "2026-08" },
  { id: "freepik", name: "Freepik AI", nameZh: "Freepik AI", category: "design", region: "overseas", description: "Freepik 平台的 AI 图像与设计工具，生成插画、图标与素材。", descriptionEn: "Freepik's AI image and design tools for illustrations, icons and assets.", officialUrl: "https://www.freepik.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["图像生成", "设计素材"], tagsEn: ["Image", "Assets"], score: 8.0, popularity: 60, emoji: "🖼️", releaseYear: 2010, model: "多模型", modelEn: "Multi-model", platforms: ["web"], verified: true, lastChecked: "2026-08" },

  // ── 补强：教育学习 ─────────────────────────────
  { id: "khanmigo", name: "Khanmigo", nameZh: "Khanmigo", category: "education", region: "overseas", description: "可汗学院的 AI 导师，提供个性化辅导与作业辅导。", descriptionEn: "Khan Academy's AI tutor for personalized learning and homework help.", officialUrl: "https://www.khanmigo.ai", pricing: "paid", pricingNote: "订阅制", tags: ["辅导", "教育"], tagsEn: ["Tutoring", "Education"], score: 8.0, popularity: 54, emoji: "🎓", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web", "ios", "android"], verified: true, lastChecked: "2026-08" },

  // ── 补强：PDF 文档 ─────────────────────────────
  { id: "chatpdf", name: "ChatPDF", nameZh: "ChatPDF", category: "pdf", region: "overseas", description: "与 PDF 对话，上传文档即可问答、总结与检索。", descriptionEn: "Chat with PDFs — upload a document to ask, summarize and search.", officialUrl: "https://www.chatpdf.com", pricing: "freemium", pricingNote: "免费额度 + 订阅", tags: ["PDF", "问答"], tagsEn: ["PDF", "Q&A"], score: 7.9, popularity: 60, emoji: "📄", releaseYear: 2023, model: "GPT", modelEn: "GPT", platforms: ["web"], lastChecked: "2026-08" },

  // ── 补强：研究学术 ─────────────────────────────
  { id: "notebooklm", name: "NotebookLM", nameZh: "NotebookLM", category: "research", region: "overseas", description: "谷歌的 AI 笔记与研究报告工具，上传资料自动生成摘要、问答与播客。", descriptionEn: "Google's AI notebook that summarizes sources and generates audio overviews.", officialUrl: "https://notebooklm.google.com", pricing: "free", pricingNote: "免费", tags: ["笔记", "研究"], tagsEn: ["Notes", "Research"], score: 8.7, popularity: 76, emoji: "📓", releaseYear: 2023, model: "Gemini", modelEn: "Gemini", platforms: ["web"], verified: true, trending: true, lastChecked: "2026-08" },
];

const tools = JSON.parse(readFileSync(dataPath, "utf8"));
const existing = new Set(tools.map((t) => t.id));

let added = 0;
const skipped = [];
for (const nt of newTools) {
  if (existing.has(nt.id)) {
    skipped.push(nt.id);
    continue;
  }
  tools.push(nt);
  added++;
}

writeFileSync(dataPath, JSON.stringify(tools, null, 2) + "\n", "utf8");
console.log(`added: ${added} new tools`);
if (skipped.length) console.log(`skipped (dup): ${skipped.join(", ")}`);
console.log(`total: ${tools.length} tools`);
