// 一次性数据迁移脚本：
// 1) 把旧的「音频音乐」拆分为「音乐生成 / 语音合成」，数字人单独成类
// 2) 追加一批海外 AI 软件，覆盖新增分类
// 用法：node scripts/expand-tools.mjs
import fs from "node:fs";
import path from "node:path";

const TOOLS_PATH = path.join(process.cwd(), "data", "tools.json");
const tools = JSON.parse(fs.readFileSync(TOOLS_PATH, "utf-8"));

// 1) 重分类：id -> 新分类
const RECATEGORY = {
  suno: "music",
  udio: "music",
  elevenlabs: "voice",
  heygen: "avatar",
};

for (const tool of tools) {
  if (RECATEGORY[tool.id]) {
    tool.category = RECATEGORY[tool.id];
    process.stdout.write(`↻ ${tool.name.padEnd(14)} → ${tool.category}\n`);
  }
}

// 2) 新增海外软件（id 已存在则跳过，保证可重复执行）
const NEW_TOOLS = [
  {
    id: "grok",
    name: "Grok",
    nameZh: "Grok",
    category: "chat",
    description: "xAI 推出的 AI 助手，深度整合 X（推特）实时信息，风格幽默直接，推理能力强。",
    officialUrl: "https://grok.com",
    pricing: "freemium",
    pricingNote: "免费额度 + X Premium",
    tags: ["对话", "推理", "实时信息"],
    score: 9.0,
    popularity: 86,
    featured: false,
    emoji: "🪐",
    releaseYear: 2023,
  },
  {
    id: "mistral",
    name: "Mistral Le Chat",
    nameZh: "Mistral Le Chat",
    category: "chat",
    description: "欧洲 AI 独角兽 Mistral 的对话助手，开源模型生态完善，多语言与代码能力强。",
    officialUrl: "https://chat.mistral.ai",
    pricing: "freemium",
    pricingNote: "免费版 + Pro",
    tags: ["对话", "开源", "欧洲"],
    score: 8.7,
    popularity: 75,
    featured: false,
    emoji: "🌬️",
    releaseYear: 2024,
  },
  {
    id: "poe",
    name: "Poe",
    nameZh: "Poe",
    category: "chat",
    description: "Quora 推出的 AI 聚合平台，一个入口即可访问 GPT、Claude、Gemini 等多个主流模型。",
    officialUrl: "https://poe.com",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["聚合", "多模型", "对话"],
    score: 8.5,
    popularity: 72,
    featured: false,
    emoji: "🎪",
    releaseYear: 2023,
  },
  {
    id: "ideogram",
    name: "Ideogram",
    nameZh: "Ideogram",
    category: "image",
    description: "擅长在图像中精准渲染文字的 AI 绘图工具，适合海报、Logo 与带字设计。",
    officialUrl: "https://ideogram.ai",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["文生图", "文字渲染", "海报"],
    score: 8.6,
    popularity: 78,
    featured: false,
    emoji: "🔡",
    releaseYear: 2023,
  },
  {
    id: "nano-banana",
    name: "Nano Banana",
    nameZh: "Nano Banana",
    category: "image-edit",
    description: "Google Gemini 的图像生成与编辑模型，以强大的图片编辑、局部重绘与「P 图」能力走红。",
    officialUrl: "https://gemini.google.com",
    pricing: "freemium",
    pricingNote: "免费额度 + Google AI Pro",
    tags: ["图片编辑", "局部重绘", "Gemini"],
    score: 9.2,
    popularity: 93,
    featured: true,
    emoji: "🍌",
    releaseYear: 2025,
  },
  {
    id: "remove-bg",
    name: "Remove.bg",
    nameZh: "Remove.bg",
    category: "image-edit",
    description: "一键智能抠图工具，自动去除图片背景，处理速度快、边缘效果好。",
    officialUrl: "https://www.remove.bg",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["抠图", "去背景", "电商"],
    score: 8.5,
    popularity: 77,
    featured: false,
    emoji: "🧹",
    releaseYear: 2018,
  },
  {
    id: "photoroom",
    name: "Photoroom",
    nameZh: "Photoroom",
    category: "image-edit",
    description: "面向电商的 AI 图片编辑工具，批量去背景、生成商品图与营销素材。",
    officialUrl: "https://www.photoroom.com",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["商品图", "去背景", "电商"],
    score: 8.3,
    popularity: 73,
    featured: false,
    emoji: "📦",
    releaseYear: 2019,
  },
  {
    id: "veo",
    name: "Veo",
    nameZh: "Veo",
    category: "video",
    description: "Google DeepMind 的文生视频模型，画质与物理一致性出色，支持高分辨率生成。",
    officialUrl: "https://deepmind.google/models/veo/",
    pricing: "paid",
    pricingNote: "订阅制",
    tags: ["文生视频", "Google", "高质量"],
    score: 9.1,
    popularity: 83,
    featured: false,
    emoji: "🎞️",
    releaseYear: 2024,
  },
  {
    id: "synthesia",
    name: "Synthesia",
    nameZh: "Synthesia",
    category: "avatar",
    description: "企业级 AI 数字人视频平台，用数字人批量生成多语言讲解与培训视频。",
    officialUrl: "https://www.synthesia.io",
    pricing: "paid",
    pricingNote: "订阅制",
    tags: ["数字人", "企业", "多语言"],
    score: 8.8,
    popularity: 79,
    featured: false,
    emoji: "🧑‍💼",
    releaseYear: 2017,
  },
  {
    id: "fish-audio",
    name: "Fish Audio",
    nameZh: "Fish Audio",
    category: "voice",
    description: "开源生态的 AI 语音合成与声音克隆平台，中文语音效果好，支持实时语音。",
    officialUrl: "https://fish.audio",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["语音合成", "声音克隆", "中文"],
    score: 8.6,
    popularity: 76,
    featured: false,
    emoji: "🐟",
    releaseYear: 2023,
  },
  {
    id: "lovable",
    name: "Lovable",
    nameZh: "Lovable",
    category: "code",
    description: "欧洲热门 AI 全栈开发平台，用自然语言即可构建并上线 Web 应用。",
    officialUrl: "https://lovable.dev",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["全栈", "Web 应用", "低代码"],
    score: 8.7,
    popularity: 80,
    featured: false,
    emoji: "❤️",
    releaseYear: 2024,
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    nameZh: "NotebookLM",
    category: "office",
    description: "Google 的 AI 笔记与深度研究工具，上传资料即可生成摘要、问答与音频概览。",
    officialUrl: "https://notebooklm.google.com",
    pricing: "free",
    pricingNote: "免费",
    tags: ["笔记", "研究", "音频概览"],
    score: 9.0,
    popularity: 84,
    featured: false,
    emoji: "📓",
    releaseYear: 2023,
  },
  {
    id: "character-ai",
    name: "Character.AI",
    nameZh: "Character.AI",
    category: "companion",
    description: "AI 角色陪伴与互动平台，可创建或与各种 AI 角色对话，情感陪伴与娱乐属性强。",
    officialUrl: "https://character.ai",
    pricing: "freemium",
    pricingNote: "免费版 + 订阅",
    tags: ["角色陪伴", "对话", "娱乐"],
    score: 8.7,
    popularity: 82,
    featured: false,
    emoji: "🎭",
    releaseYear: 2022,
  },
  {
    id: "talkie",
    name: "Talkie",
    nameZh: "Talkie（星野）",
    category: "companion",
    description: "MiniMax 推出的 AI 角色陪伴与互动平台（国内对应「星野」），支持语音与角色扮演。",
    officialUrl: "https://www.talkie-ai.com",
    pricing: "freemium",
    pricingNote: "免费版 + 订阅",
    tags: ["角色陪伴", "语音", "互动"],
    score: 8.4,
    popularity: 74,
    featured: false,
    emoji: "⭐",
    releaseYear: 2023,
  },
  {
    id: "replika",
    name: "Replika",
    nameZh: "Replika",
    category: "companion",
    description: "AI 虚拟伴侣应用，可进行个性化聊天与情感陪伴，支持文字与语音互动。",
    officialUrl: "https://replika.com",
    pricing: "freemium",
    pricingNote: "免费版 + Pro",
    tags: ["虚拟伴侣", "情感陪伴", "语音"],
    score: 8.2,
    popularity: 71,
    featured: false,
    emoji: "💖",
    releaseYear: 2017,
  },
];

const existing = new Set(tools.map((t) => t.id));
let added = 0;
for (const nt of NEW_TOOLS) {
  if (existing.has(nt.id)) continue;
  tools.push(nt);
  existing.add(nt.id);
  process.stdout.write(`+ ${nt.name.padEnd(18)} ${nt.category}\n`);
  added++;
}

fs.writeFileSync(TOOLS_PATH, JSON.stringify(tools, null, 2) + "\n", "utf-8");
console.log(
  `\n完成：新增 ${added} 款，当前共 ${tools.length} 款软件。`,
);
