// 二次扩充（参考 ai-bot.cn）：
// 1) 追加一批我们缺失的 AI 工具（国内 + 海外）
// 2) 给全部工具补充「国内 / 海外」region 标签
// 用法：node scripts/expand-region.mjs
import fs from "node:fs";
import path from "node:path";

const TOOLS_PATH = path.join(process.cwd(), "data", "tools.json");
const tools = JSON.parse(fs.readFileSync(TOOLS_PATH, "utf-8"));

// 国内（中国团队/可直连）产品 id 清单，其余默认标记为海外
const DOMESTIC = new Set([
  // 已有
  "deepseek", "kimi", "doubao", "wenxin", "tongyi", "chatglm", "yuanbao",
  "jimeng", "yige",
  "kling", "hailuo",
  "lingma",
  "wps-ai", "feishu", "dingtalk", "xinghuo",
  "xiezuocat",
  "metaso", "tiangong",
  "youdao", "immersive",
  "gaoding",
  "fish-audio", "talkie",
  // 新增
  "zhipu-qingying", "vidu", "bcut", "wanxiang", "seaart",
  "aippt", "wanzhi", "xunfei-zhiwen",
  "marscode", "codegeex",
  "devv", "quark",
  "baidu-translate",
  "stepfun",
]);

const NEW_TOOLS = [
  {
    id: "zhipu-qingying",
    name: "智谱清影",
    nameZh: "智谱清影",
    category: "video",
    description: "智谱 AI 推出的视频生成工具，基于 CogVideo 模型，支持文生视频与图生视频。",
    officialUrl: "https://chatglm.cn/video",
    pricing: "freemium",
    pricingNote: "免费额度 + 会员",
    tags: ["文生视频", "中文", "CogVideo"],
    score: 8.5,
    popularity: 78,
    featured: false,
    emoji: "📽️",
    releaseYear: 2024,
  },
  {
    id: "vidu",
    name: "Vidu",
    nameZh: "Vidu（生数科技）",
    category: "video",
    description: "生数科技推出的文生视频与图生视频大模型，生成速度快、动作连贯。",
    officialUrl: "https://www.vidu.cn",
    pricing: "freemium",
    pricingNote: "免费额度 + 会员",
    tags: ["文生视频", "图生视频", "中文"],
    score: 8.6,
    popularity: 80,
    featured: false,
    emoji: "🪩",
    releaseYear: 2024,
  },
  {
    id: "bcut",
    name: "必剪 Studio",
    nameZh: "必剪 Studio",
    category: "video",
    description: "哔哩哔哩旗下的视频剪辑工具，内置 AI 字幕、数字人与智能剪辑能力。",
    officialUrl: "https://bcut.drawyoo.com",
    pricing: "free",
    pricingNote: "免费",
    tags: ["视频剪辑", "字幕", "数字人"],
    score: 8.2,
    popularity: 75,
    featured: false,
    emoji: "🎬",
    releaseYear: 2021,
  },
  {
    id: "krea",
    name: "Krea",
    nameZh: "Krea",
    category: "video",
    description: "实时 AI 图像与视频生成平台，支持实时绘制与视频增强，创作者社区活跃。",
    officialUrl: "https://www.krea.ai",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["实时生成", "视频", "图像"],
    score: 8.6,
    popularity: 79,
    featured: false,
    emoji: "🕹️",
    releaseYear: 2023,
  },
  {
    id: "wanxiang",
    name: "通义万相",
    nameZh: "通义万相",
    category: "image",
    description: "阿里云推出的 AI 绘画与图像生成模型，中文理解好，支持多种风格与视频。",
    officialUrl: "https://tongyi.aliyun.com/wanxiang",
    pricing: "freemium",
    pricingNote: "免费额度 + 会员",
    tags: ["文生图", "中文", "阿里云"],
    score: 8.5,
    popularity: 78,
    featured: false,
    emoji: "🪆",
    releaseYear: 2023,
  },
  {
    id: "firefly",
    name: "Adobe Firefly",
    nameZh: "Adobe Firefly",
    category: "image",
    description: "Adobe 推出的生成式 AI 图像工具，深度整合 Photoshop，擅长商业安全素材。",
    officialUrl: "https://firefly.adobe.com",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["文生图", "Adobe", "商业安全"],
    score: 8.8,
    popularity: 81,
    featured: false,
    emoji: "🪶",
    releaseYear: 2023,
  },
  {
    id: "playground",
    name: "Playground",
    nameZh: "Playground",
    category: "image",
    description: "易上手的 AI 图像与设计平台，支持图形化界面生成海报、Logo 与图标。",
    officialUrl: "https://playground.com",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["文生图", "海报", "Logo"],
    score: 8.3,
    popularity: 72,
    featured: false,
    emoji: "🎠",
    releaseYear: 2023,
  },
  {
    id: "seaart",
    name: "SeaArt",
    nameZh: "SeaArt（海艺）",
    category: "image",
    description: "国产 AI 绘画平台，模型丰富、模板海量，支持文生图、图生图与模型训练。",
    officialUrl: "https://www.seaart.ai",
    pricing: "freemium",
    pricingNote: "免费额度 + 会员",
    tags: ["文生图", "模型丰富", "训练"],
    score: 8.2,
    popularity: 74,
    featured: false,
    emoji: "🌊",
    releaseYear: 2023,
  },
  {
    id: "aippt",
    name: "AiPPT",
    nameZh: "AiPPT",
    category: "office",
    description: "AI 一键生成 PPT 大纲与演示文稿，输入主题即可产出完整可编辑的 PPT。",
    officialUrl: "https://www.aippt.cn",
    pricing: "freemium",
    pricingNote: "免费额度 + 会员",
    tags: ["PPT", "演示", "一键生成"],
    score: 8.4,
    popularity: 76,
    featured: false,
    emoji: "📑",
    releaseYear: 2023,
  },
  {
    id: "wanzhi",
    name: "万知",
    nameZh: "万知",
    category: "office",
    description: "零一万物推出的 AI 办公助手，支持文档解读、写作与知识问答。",
    officialUrl: "https://www.wanzhi.com",
    pricing: "free",
    pricingNote: "免费",
    tags: ["文档", "写作", "问答"],
    score: 8.3,
    popularity: 73,
    featured: false,
    emoji: "📚",
    releaseYear: 2024,
  },
  {
    id: "xunfei-zhiwen",
    name: "讯飞智文",
    nameZh: "讯飞智文",
    category: "office",
    description: "科大讯飞推出的 AI 文档写作工具，支持一键生成 Word/PPT 与智能排版。",
    officialUrl: "https://zhiwen.xfyun.cn",
    pricing: "freemium",
    pricingNote: "免费额度 + 会员",
    tags: ["文档", "PPT", "智能排版"],
    score: 8.2,
    popularity: 72,
    featured: false,
    emoji: "🗂️",
    releaseYear: 2023,
  },
  {
    id: "marscode",
    name: "MarsCode",
    nameZh: "MarsCode（字节）",
    category: "code",
    description: "字节跳动推出的 AI 编程助手与云端 IDE，支持代码补全、Agent 与一键部署。",
    officialUrl: "https://www.marscode.cn",
    pricing: "free",
    pricingNote: "免费",
    tags: ["AI IDE", "代码补全", "字节"],
    score: 8.6,
    popularity: 79,
    featured: false,
    emoji: "🧑‍🚀",
    releaseYear: 2024,
  },
  {
    id: "codegeex",
    name: "CodeGeeX",
    nameZh: "CodeGeeX（智谱）",
    category: "code",
    description: "智谱 AI 推出的 AI 编程助手，开源模型驱动，支持多语言代码生成与补全。",
    officialUrl: "https://codegeex.cn",
    pricing: "free",
    pricingNote: "免费",
    tags: ["代码补全", "开源", "多语言"],
    score: 8.4,
    popularity: 74,
    featured: false,
    emoji: "⚙️",
    releaseYear: 2022,
  },
  {
    id: "cline",
    name: "Cline",
    nameZh: "Cline",
    category: "code",
    description: "开源 AI 编程智能体，可在 VS Code 中自动规划、读写代码并执行任务。",
    officialUrl: "https://cline.bot",
    pricing: "freemium",
    pricingNote: "开源免费 + API 计费",
    tags: ["Agent", "开源", "VS Code"],
    score: 8.7,
    popularity: 78,
    featured: false,
    emoji: "🛠️",
    releaseYear: 2024,
  },
  {
    id: "aider",
    name: "Aider",
    nameZh: "Aider",
    category: "code",
    description: "终端 AI 结对编程工具，支持多文件编辑与 Git 集成，开源免费。",
    officialUrl: "https://aider.chat",
    pricing: "free",
    pricingNote: "开源免费 + API 计费",
    tags: ["终端", "Git", "开源"],
    score: 8.5,
    popularity: 73,
    featured: false,
    emoji: "🔧",
    releaseYear: 2023,
  },
  {
    id: "paperpal",
    name: "Paperpal",
    nameZh: "Paperpal",
    category: "writing",
    description: "面向学术写作的 AI 润色工具，专精论文语法、用词与期刊投稿规范。",
    officialUrl: "https://paperpal.com",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["学术", "英文润色", "论文"],
    score: 8.3,
    popularity: 70,
    featured: false,
    emoji: "🎓",
    releaseYear: 2022,
  },
  {
    id: "devv",
    name: "Devv",
    nameZh: "Devv",
    category: "search",
    description: "面向开发者的 AI 搜索引擎，聚焦技术问答与代码检索，结果精准。",
    officialUrl: "https://devv.ai",
    pricing: "freemium",
    pricingNote: "免费额度 + 订阅",
    tags: ["开发者", "搜索", "代码"],
    score: 8.5,
    popularity: 75,
    featured: false,
    emoji: "🖥️",
    releaseYear: 2023,
  },
  {
    id: "quark",
    name: "夸克 AI",
    nameZh: "夸克 AI",
    category: "search",
    description: "阿里旗下夸克浏览器的 AI 助手，集搜索、问答与文件处理于一体。",
    officialUrl: "https://www.quark.cn",
    pricing: "free",
    pricingNote: "免费",
    tags: ["搜索", "浏览器", "问答"],
    score: 8.3,
    popularity: 76,
    featured: false,
    emoji: "🧭",
    releaseYear: 2023,
  },
  {
    id: "baidu-translate",
    name: "百度翻译",
    nameZh: "百度翻译",
    category: "translate",
    description: "百度推出的翻译工具，支持 200+ 语言互译、拍照翻译与文档翻译。",
    officialUrl: "https://fanyi.baidu.com",
    pricing: "free",
    pricingNote: "免费",
    tags: ["翻译", "多语言", "文档"],
    score: 8.2,
    popularity: 72,
    featured: false,
    emoji: "🐻",
    releaseYear: 2011,
  },
  {
    id: "figjam",
    name: "FigJam AI",
    nameZh: "FigJam AI",
    category: "design",
    description: "Figma 推出的在线协作白板，内置 AI 生成便签、总结与流程图。",
    officialUrl: "https://www.figma.com/figjam",
    pricing: "freemium",
    pricingNote: "免费版 + 付费版",
    tags: ["白板", "协作", "流程图"],
    score: 8.4,
    popularity: 73,
    featured: false,
    emoji: "📋",
    releaseYear: 2021,
  },
  {
    id: "ms-designer",
    name: "Microsoft Designer",
    nameZh: "Microsoft Designer",
    category: "design",
    description: "微软推出的 AI 设计工具，输入描述即可生成海报、邀请函与社媒配图。",
    officialUrl: "https://designer.microsoft.com",
    pricing: "freemium",
    pricingNote: "免费额度 + Copilot 订阅",
    tags: ["海报", "社媒配图", "微软"],
    score: 8.4,
    popularity: 74,
    featured: false,
    emoji: "🪟",
    releaseYear: 2023,
  },
  {
    id: "stepfun",
    name: "阶跃星辰",
    nameZh: "阶跃星辰（跃问）",
    category: "chat",
    description: "阶跃星辰推出的大模型平台与「跃问」助手，多模态与长文本能力强。",
    officialUrl: "https://www.stepfun.com",
    pricing: "freemium",
    pricingNote: "免费版 + API 计费",
    tags: ["对话", "多模态", "长文本"],
    score: 8.4,
    popularity: 74,
    featured: false,
    emoji: "🪜",
    releaseYear: 2023,
  },
];

const existing = new Set(tools.map((t) => t.id));
let added = 0;
for (const nt of NEW_TOOLS) {
  if (existing.has(nt.id)) continue;
  tools.push(nt);
  existing.add(nt.id);
  added++;
}

// 统一打 region 标签
let domestic = 0;
for (const tool of tools) {
  tool.region = DOMESTIC.has(tool.id) ? "domestic" : "overseas";
  if (tool.region === "domestic") domestic++;
}

fs.writeFileSync(TOOLS_PATH, JSON.stringify(tools, null, 2) + "\n", "utf-8");
console.log(
  `完成：新增 ${added} 款，当前共 ${tools.length} 款；国内 ${domestic} 款，海外 ${tools.length - domestic} 款。`,
);
