import type { Metadata } from "next";
import Link from "next/link";
import { BilingualText } from "@/components/Bilingual";
import { getPricingRecord, pricingCoverage, pricingRecords } from "@/lib/pricing-database";
import { getTool } from "@/lib/tools";
import { getPreferredVariant, variantRoutes } from "@/lib/product-variants";

export const metadata: Metadata = { title: "AI Tool Pricing Database", description: "Structured AI tool pricing records with official sources, verification status, billing intervals and transparent data gaps.", alternates: { canonical: "/pricing" } };
const detailHref = (toolId: string) => { const tool = getTool(toolId); if (!tool) return `/tools/${toolId}`; const variant = getPreferredVariant(tool); return variant ? `/${variantRoutes[variant]}/${toolId}` : `/tools/${toolId}`; };

export default function PricingDatabasePage() {
  const coverage = pricingCoverage(); const sourced = pricingRecords.filter((record) => record.sourceUrl).sort((a, b) => a.toolId.localeCompare(b.toolId));
  return <main className="min-h-screen bg-[#f2f4ef] text-[#0b1b17]">
    <header className="border-b border-[#27443b] bg-[#07110f] text-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:py-20"><h1 className="max-w-4xl text-4xl leading-tight sm:text-6xl"><BilingualText zh="AI 工具价格数据库" en="AI tool pricing, with an evidence trail" /></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#b9c9c2]"><BilingualText zh="套餐不是一段营销文字。这里分别保存金额、币种、计费周期、官方来源、核验日期和历史变化。" en="Pricing is not a marketing sentence. Amounts, currencies, billing intervals, official sources, verification dates and historical changes are stored separately." /></p><div className="mt-10 grid gap-px bg-[#315148] sm:grid-cols-3 lg:grid-cols-6">{[[coverage.total,"产品记录","Product records"],[coverage.withPlans,"含套餐","With plans"],[coverage.withOfficialSource,"官方来源","Official sources"],[coverage.verified,"已核验","Verified"],[coverage.source_pending,"待核验","Source pending"],[coverage.legacy_unverified,"历史导入","Legacy imports"]].map(([value,zh,en]) => <div key={String(en)} className="bg-[#0a1815] p-4"><div className="font-mono text-2xl text-[#d9f99d]">{value}</div><div className="mt-1 text-xs uppercase text-[#8fa39b]"><BilingualText zh={String(zh)} en={String(en)} /></div></div>)}</div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><section className="grid gap-8 border-b border-[#aebbb4] pb-10 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-2xl font-semibold"><BilingualText zh="核验规则" en="Verification rules" /></h2><p className="mt-3 leading-7 text-[#596761]"><BilingualText zh="只有同时具备官方来源和明确核验日期的记录，才能显示为已核验。链接存在但尚未逐项检查时，只能显示等待核验。" en="A record becomes verified only when it has both a first-party source and an explicit verification date. A linked source without a plan-by-plan review remains pending." /></p></div><dl className="grid gap-px bg-[#c2cbc5] sm:grid-cols-3"><div className="bg-white p-5"><dt className="font-semibold text-[#174638]"><BilingualText zh="已核验" en="Verified" /></dt><dd className="mt-2 text-sm leading-6 text-[#596761]"><BilingualText zh="官方来源、套餐字段和日期齐全。" en="Official source, plan fields and date are present." /></dd></div><div className="bg-white p-5"><dt className="font-semibold text-[#17445a]"><BilingualText zh="等待核验" en="Source pending" /></dt><dd className="mt-2 text-sm leading-6 text-[#596761]"><BilingualText zh="已有官方页面，但套餐尚未逐项复核。" en="An official page exists, but plans need review." /></dd></div><div className="bg-white p-5"><dt className="font-semibold text-[#704d1f]"><BilingualText zh="历史导入" en="Legacy import" /></dt><dd className="mt-2 text-sm leading-6 text-[#596761]"><BilingualText zh="旧数据保留，但不宣称为当前价格。" en="Old data is retained without a current-price claim." /></dd></div></dl></section>
      <section className="py-10"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-3xl font-semibold"><BilingualText zh="已有官方价格来源" en="Official pricing sources in queue" /></h2><p className="mt-2 text-sm text-[#596761]"><BilingualText zh="优先核验这些高流量产品。" en="These high-intent products are first in the verification queue." /></p></div><span className="font-mono text-xs text-[#68766f]">{sourced.length} SOURCE RECORDS</span></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead className="bg-[#07110f] text-white"><tr><th className="p-4"><BilingualText zh="产品" en="Product" /></th><th className="p-4"><BilingualText zh="套餐数" en="Plans" /></th><th className="p-4"><BilingualText zh="状态" en="Status" /></th><th className="p-4"><BilingualText zh="核验日期" en="Verified at" /></th><th className="p-4"><BilingualText zh="来源" en="Source" /></th></tr></thead><tbody>{sourced.map((record) => { const tool = getTool(record.toolId); const live = getPricingRecord(record.toolId); return <tr key={record.toolId} className="border-b border-[#c2cbc5]"><td className="p-4"><Link href={detailHref(record.toolId)} className="font-semibold text-[#174638] hover:underline">{tool?.name ?? record.toolId}</Link></td><td className="p-4 font-mono">{live?.plans.length ?? 0}</td><td className="p-4"><BilingualText zh={record.status === "verified" ? "已核验" : "等待核验"} en={record.status === "verified" ? "Verified" : "Source pending"} /></td><td className="p-4 font-mono">{record.verifiedAt ?? "—"}</td><td className="p-4"><a href={record.sourceUrl ?? "#"} target="_blank" rel="noopener noreferrer" className="font-semibold text-[#285c4c] underline underline-offset-4">{record.sourceLabel ?? "Official pricing"}</a></td></tr>; })}</tbody></table></div></section>
    </div>
  </main>;
}
